// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/auth_v2.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// V2 User model with enhanced fields
type UserV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	IsValidated   bool                   `protobuf:"varint,5,opt,name=is_validated,json=isValidated,proto3" json:"is_validated,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UserRoles     []*UserRoleV2          `protobuf:"bytes,9,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	Permissions   []string               `protobuf:"bytes,10,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserV2) Reset() {
	*x = UserV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserV2) ProtoMessage() {}

func (x *UserV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserV2.ProtoReflect.Descriptor instead.
func (*UserV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{0}
}

func (x *UserV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserV2) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserV2) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserV2) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserV2) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

func (x *UserV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserV2) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserV2) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *UserV2) GetUserRoles() []*UserRoleV2 {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *UserV2) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// V2 UserRole model
type UserRoleV2 struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId          string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName        string                 `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleDescription string                 `protobuf:"bytes,5,opt,name=role_description,json=roleDescription,proto3" json:"role_description,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserRoleV2) Reset() {
	*x = UserRoleV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRoleV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRoleV2) ProtoMessage() {}

func (x *UserRoleV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRoleV2.ProtoReflect.Descriptor instead.
func (*UserRoleV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{1}
}

func (x *UserRoleV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserRoleV2) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRoleV2) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UserRoleV2) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *UserRoleV2) GetRoleDescription() string {
	if x != nil {
		return x.RoleDescription
	}
	return ""
}

func (x *UserRoleV2) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *UserRoleV2) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// V2 Login Request
type LoginRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MfaCode       string                 `protobuf:"bytes,3,opt,name=mfa_code,json=mfaCode,proto3" json:"mfa_code,omitempty"` // Optional MFA code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestV2) Reset() {
	*x = LoginRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestV2) ProtoMessage() {}

func (x *LoginRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestV2.ProtoReflect.Descriptor instead.
func (*LoginRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequestV2) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequestV2) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequestV2) GetMfaCode() string {
	if x != nil {
		return x.MfaCode
	}
	return ""
}

// V2 Login Response
type LoginResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,6,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	User          *UserV2                `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Permissions   []string               `protobuf:"bytes,8,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponseV2) Reset() {
	*x = LoginResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponseV2) ProtoMessage() {}

func (x *LoginResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponseV2.ProtoReflect.Descriptor instead.
func (*LoginResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LoginResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponseV2) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponseV2) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponseV2) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *LoginResponseV2) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *LoginResponseV2) GetUser() *UserV2 {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *LoginResponseV2) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// V2 Register Request
type RegisterRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	RoleIds       []string               `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestV2) Reset() {
	*x = RegisterRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestV2) ProtoMessage() {}

func (x *RegisterRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestV2.ProtoReflect.Descriptor instead.
func (*RegisterRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequestV2) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequestV2) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequestV2) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *RegisterRequestV2) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequestV2) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// V2 Register Response
type RegisterResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *UserV2                `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponseV2) Reset() {
	*x = RegisterResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponseV2) ProtoMessage() {}

func (x *RegisterResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponseV2.ProtoReflect.Descriptor instead.
func (*RegisterResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RegisterResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterResponseV2) GetUser() *UserV2 {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *RegisterResponseV2) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RegisterResponseV2) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// V2 Get User Request
type GetUserRequestV2 struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludeRoles       bool                   `protobuf:"varint,2,opt,name=include_roles,json=includeRoles,proto3" json:"include_roles,omitempty"`
	IncludePermissions bool                   `protobuf:"varint,3,opt,name=include_permissions,json=includePermissions,proto3" json:"include_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetUserRequestV2) Reset() {
	*x = GetUserRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequestV2) ProtoMessage() {}

func (x *GetUserRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequestV2.ProtoReflect.Descriptor instead.
func (*GetUserRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserRequestV2) GetIncludeRoles() bool {
	if x != nil {
		return x.IncludeRoles
	}
	return false
}

func (x *GetUserRequestV2) GetIncludePermissions() bool {
	if x != nil {
		return x.IncludePermissions
	}
	return false
}

// V2 Get User Response
type GetUserResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *UserV2                `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponseV2) Reset() {
	*x = GetUserResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponseV2) ProtoMessage() {}

func (x *GetUserResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponseV2.ProtoReflect.Descriptor instead.
func (*GetUserResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetUserResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetUserResponseV2) GetUser() *UserV2 {
	if x != nil {
		return x.User
	}
	return nil
}

// V2 Get All Users Request
type GetAllUsersRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	RoleIds       []string               `protobuf:"bytes,5,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequestV2) Reset() {
	*x = GetAllUsersRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequestV2) ProtoMessage() {}

func (x *GetAllUsersRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequestV2.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllUsersRequestV2) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllUsersRequestV2) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAllUsersRequestV2) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllUsersRequestV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAllUsersRequestV2) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// V2 Get All Users Response
type GetAllUsersResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Users         []*UserV2              `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponseV2) Reset() {
	*x = GetAllUsersResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponseV2) ProtoMessage() {}

func (x *GetAllUsersResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponseV2.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllUsersResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAllUsersResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllUsersResponseV2) GetUsers() []*UserV2 {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GetAllUsersResponseV2) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAllUsersResponseV2) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllUsersResponseV2) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// V2 Update User Request
type UpdateUserRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	IsValidated   bool                   `protobuf:"varint,5,opt,name=is_validated,json=isValidated,proto3" json:"is_validated,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	RoleIds       []string               `protobuf:"bytes,7,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequestV2) Reset() {
	*x = UpdateUserRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequestV2) ProtoMessage() {}

func (x *UpdateUserRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequestV2.ProtoReflect.Descriptor instead.
func (*UpdateUserRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequestV2) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequestV2) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequestV2) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateUserRequestV2) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

func (x *UpdateUserRequestV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateUserRequestV2) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

// V2 Update User Response
type UpdateUserResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	User          *UserV2                `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponseV2) Reset() {
	*x = UpdateUserResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponseV2) ProtoMessage() {}

func (x *UpdateUserResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponseV2.ProtoReflect.Descriptor instead.
func (*UpdateUserResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateUserResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateUserResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserResponseV2) GetUser() *UserV2 {
	if x != nil {
		return x.User
	}
	return nil
}

// V2 Delete User Request
type DeleteUserRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequestV2) Reset() {
	*x = DeleteUserRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequestV2) ProtoMessage() {}

func (x *DeleteUserRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequestV2.ProtoReflect.Descriptor instead.
func (*DeleteUserRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// V2 Delete User Response
type DeleteUserResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponseV2) Reset() {
	*x = DeleteUserResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponseV2) ProtoMessage() {}

func (x *DeleteUserResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponseV2.ProtoReflect.Descriptor instead.
func (*DeleteUserResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteUserResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// V2 Refresh Token Request
type RefreshTokenRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequestV2) Reset() {
	*x = RefreshTokenRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequestV2) ProtoMessage() {}

func (x *RefreshTokenRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequestV2.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTokenRequestV2) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// V2 Refresh Token Response
type RefreshTokenResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int32                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponseV2) Reset() {
	*x = RefreshTokenResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponseV2) ProtoMessage() {}

func (x *RefreshTokenResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponseV2.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{15}
}

func (x *RefreshTokenResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RefreshTokenResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshTokenResponseV2) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponseV2) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponseV2) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// V2 Logout Request
type LogoutRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequestV2) Reset() {
	*x = LogoutRequestV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequestV2) ProtoMessage() {}

func (x *LogoutRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequestV2.ProtoReflect.Descriptor instead.
func (*LogoutRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{16}
}

func (x *LogoutRequestV2) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// V2 Logout Response
type LogoutResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponseV2) Reset() {
	*x = LogoutResponseV2{}
	mi := &file_proto_auth_v2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponseV2) ProtoMessage() {}

func (x *LogoutResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_v2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponseV2.ProtoReflect.Descriptor instead.
func (*LogoutResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_auth_v2_proto_rawDescGZIP(), []int{17}
}

func (x *LogoutResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *LogoutResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_auth_v2_proto protoreflect.FileDescriptor

const file_proto_auth_v2_proto_rawDesc = "" +
	"\n" +
	"\x13proto/auth_v2.proto\x12\x02pb\"\xb1\x02\n" +
	"\x06UserV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12!\n" +
	"\fis_validated\x18\x05 \x01(\bR\visValidated\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12-\n" +
	"\n" +
	"user_roles\x18\t \x03(\v2\x0e.pb.UserRoleV2R\tuserRoles\x12 \n" +
	"\vpermissions\x18\n" +
	" \x03(\tR\vpermissions\"\xd4\x01\n" +
	"\n" +
	"UserRoleV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x04 \x01(\tR\broleName\x12)\n" +
	"\x10role_description\x18\x05 \x01(\tR\x0froleDescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"c\n" +
	"\x0eLoginRequestV2\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x19\n" +
	"\bmfa_code\x18\x03 \x01(\tR\amfaCode\"\x94\x02\n" +
	"\x0fLoginResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x06 \x01(\x05R\texpiresIn\x12\x1e\n" +
	"\x04user\x18\a \x01(\v2\n" +
	".pb.UserV2R\x04user\x12 \n" +
	"\vpermissions\x18\b \x03(\tR\vpermissions\"\x99\x01\n" +
	"\x11RegisterRequestV2\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x19\n" +
	"\brole_ids\x18\x05 \x03(\tR\aroleIds\"\xb7\x01\n" +
	"\x12RegisterResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".pb.UserV2R\x04user\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\"x\n" +
	"\x10GetUserRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinclude_roles\x18\x02 \x01(\bR\fincludeRoles\x12/\n" +
	"\x13include_permissions\x18\x03 \x01(\bR\x12includePermissions\"n\n" +
	"\x11GetUserResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".pb.UserV2R\x04user\"\x90\x01\n" +
	"\x14GetAllUsersRequestV2\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x19\n" +
	"\brole_ids\x18\x05 \x03(\tR\aroleIds\"\xc4\x01\n" +
	"\x15GetAllUsersResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\x05users\x18\x03 \x03(\v2\n" +
	".pb.UserV2R\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x06 \x01(\x05R\aperPage\"\xca\x01\n" +
	"\x13UpdateUserRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12!\n" +
	"\fis_validated\x18\x05 \x01(\bR\visValidated\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x19\n" +
	"\brole_ids\x18\a \x03(\tR\aroleIds\"q\n" +
	"\x14UpdateUserResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1e\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".pb.UserV2R\x04user\"%\n" +
	"\x13DeleteUserRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x14DeleteUserResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"<\n" +
	"\x15RefreshTokenRequestV2\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\xba\x01\n" +
	"\x16RefreshTokenResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x05R\texpiresIn\"4\n" +
	"\x0fLogoutRequestV2\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"M\n" +
	"\x10LogoutResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf6\x03\n" +
	"\rUserServiceV2\x120\n" +
	"\x05Login\x12\x12.pb.LoginRequestV2\x1a\x13.pb.LoginResponseV2\x129\n" +
	"\bRegister\x12\x15.pb.RegisterRequestV2\x1a\x16.pb.RegisterResponseV2\x126\n" +
	"\aGetUser\x12\x14.pb.GetUserRequestV2\x1a\x15.pb.GetUserResponseV2\x12B\n" +
	"\vGetAllUsers\x12\x18.pb.GetAllUsersRequestV2\x1a\x19.pb.GetAllUsersResponseV2\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.pb.UpdateUserRequestV2\x1a\x18.pb.UpdateUserResponseV2\x12?\n" +
	"\n" +
	"DeleteUser\x12\x17.pb.DeleteUserRequestV2\x1a\x18.pb.DeleteUserResponseV2\x12E\n" +
	"\fRefreshToken\x12\x19.pb.RefreshTokenRequestV2\x1a\x1a.pb.RefreshTokenResponseV2\x123\n" +
	"\x06Logout\x12\x13.pb.LogoutRequestV2\x1a\x14.pb.LogoutResponseV2B%Z#github.com/Kisanlink/aaa-service/pbb\x06proto3"

var (
	file_proto_auth_v2_proto_rawDescOnce sync.Once
	file_proto_auth_v2_proto_rawDescData []byte
)

func file_proto_auth_v2_proto_rawDescGZIP() []byte {
	file_proto_auth_v2_proto_rawDescOnce.Do(func() {
		file_proto_auth_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_v2_proto_rawDesc), len(file_proto_auth_v2_proto_rawDesc)))
	})
	return file_proto_auth_v2_proto_rawDescData
}

var file_proto_auth_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_auth_v2_proto_goTypes = []any{
	(*UserV2)(nil),                 // 0: pb.UserV2
	(*UserRoleV2)(nil),             // 1: pb.UserRoleV2
	(*LoginRequestV2)(nil),         // 2: pb.LoginRequestV2
	(*LoginResponseV2)(nil),        // 3: pb.LoginResponseV2
	(*RegisterRequestV2)(nil),      // 4: pb.RegisterRequestV2
	(*RegisterResponseV2)(nil),     // 5: pb.RegisterResponseV2
	(*GetUserRequestV2)(nil),       // 6: pb.GetUserRequestV2
	(*GetUserResponseV2)(nil),      // 7: pb.GetUserResponseV2
	(*GetAllUsersRequestV2)(nil),   // 8: pb.GetAllUsersRequestV2
	(*GetAllUsersResponseV2)(nil),  // 9: pb.GetAllUsersResponseV2
	(*UpdateUserRequestV2)(nil),    // 10: pb.UpdateUserRequestV2
	(*UpdateUserResponseV2)(nil),   // 11: pb.UpdateUserResponseV2
	(*DeleteUserRequestV2)(nil),    // 12: pb.DeleteUserRequestV2
	(*DeleteUserResponseV2)(nil),   // 13: pb.DeleteUserResponseV2
	(*RefreshTokenRequestV2)(nil),  // 14: pb.RefreshTokenRequestV2
	(*RefreshTokenResponseV2)(nil), // 15: pb.RefreshTokenResponseV2
	(*LogoutRequestV2)(nil),        // 16: pb.LogoutRequestV2
	(*LogoutResponseV2)(nil),       // 17: pb.LogoutResponseV2
}
var file_proto_auth_v2_proto_depIdxs = []int32{
	1,  // 0: pb.UserV2.user_roles:type_name -> pb.UserRoleV2
	0,  // 1: pb.LoginResponseV2.user:type_name -> pb.UserV2
	0,  // 2: pb.RegisterResponseV2.user:type_name -> pb.UserV2
	0,  // 3: pb.GetUserResponseV2.user:type_name -> pb.UserV2
	0,  // 4: pb.GetAllUsersResponseV2.users:type_name -> pb.UserV2
	0,  // 5: pb.UpdateUserResponseV2.user:type_name -> pb.UserV2
	2,  // 6: pb.UserServiceV2.Login:input_type -> pb.LoginRequestV2
	4,  // 7: pb.UserServiceV2.Register:input_type -> pb.RegisterRequestV2
	6,  // 8: pb.UserServiceV2.GetUser:input_type -> pb.GetUserRequestV2
	8,  // 9: pb.UserServiceV2.GetAllUsers:input_type -> pb.GetAllUsersRequestV2
	10, // 10: pb.UserServiceV2.UpdateUser:input_type -> pb.UpdateUserRequestV2
	12, // 11: pb.UserServiceV2.DeleteUser:input_type -> pb.DeleteUserRequestV2
	14, // 12: pb.UserServiceV2.RefreshToken:input_type -> pb.RefreshTokenRequestV2
	16, // 13: pb.UserServiceV2.Logout:input_type -> pb.LogoutRequestV2
	3,  // 14: pb.UserServiceV2.Login:output_type -> pb.LoginResponseV2
	5,  // 15: pb.UserServiceV2.Register:output_type -> pb.RegisterResponseV2
	7,  // 16: pb.UserServiceV2.GetUser:output_type -> pb.GetUserResponseV2
	9,  // 17: pb.UserServiceV2.GetAllUsers:output_type -> pb.GetAllUsersResponseV2
	11, // 18: pb.UserServiceV2.UpdateUser:output_type -> pb.UpdateUserResponseV2
	13, // 19: pb.UserServiceV2.DeleteUser:output_type -> pb.DeleteUserResponseV2
	15, // 20: pb.UserServiceV2.RefreshToken:output_type -> pb.RefreshTokenResponseV2
	17, // 21: pb.UserServiceV2.Logout:output_type -> pb.LogoutResponseV2
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_auth_v2_proto_init() }
func file_proto_auth_v2_proto_init() {
	if File_proto_auth_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_v2_proto_rawDesc), len(file_proto_auth_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_v2_proto_goTypes,
		DependencyIndexes: file_proto_auth_v2_proto_depIdxs,
		MessageInfos:      file_proto_auth_v2_proto_msgTypes,
	}.Build()
	File_proto_auth_v2_proto = out.File
	file_proto_auth_v2_proto_goTypes = nil
	file_proto_auth_v2_proto_depIdxs = nil
}
