// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/role_permission.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Base message definition (optional, if you want to reuse fields like ID, createdAt, updatedAt)
type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                // UUID as string
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 timestamp
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // ISO 8601 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_proto_role_permission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Base) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Base) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Role message definition
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // Primary key (UUID as string)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Unique name
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Optional description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_role_permission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Permission message definition
type Permission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // Primary key (UUID as string)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // Unique name
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Optional description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Permission) Reset() {
	*x = Permission{}
	mi := &file_proto_role_permission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permission) ProtoMessage() {}

func (x *Permission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permission.ProtoReflect.Descriptor instead.
func (*Permission) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{2}
}

func (x *Permission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Permission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Permission) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Request messages for Role CRUD operations
type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Unique name
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Optional description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Role          *Role                  `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                                // Created role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetAllRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRolesRequest) Reset() {
	*x = GetAllRolesRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRolesRequest) ProtoMessage() {}

func (x *GetAllRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRolesRequest.ProtoReflect.Descriptor instead.
func (*GetAllRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{5}
}

type GetAllRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Roles         []*Role                `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`                              // List of roles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRolesResponse) Reset() {
	*x = GetAllRolesResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRolesResponse) ProtoMessage() {}

func (x *GetAllRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRolesResponse.ProtoReflect.Descriptor instead.
func (*GetAllRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllRolesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAllRolesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetRoleByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Role ID (UUID as string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleByIdRequest) Reset() {
	*x = GetRoleByIdRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleByIdRequest) ProtoMessage() {}

func (x *GetRoleByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleByIdRequest.ProtoReflect.Descriptor instead.
func (*GetRoleByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{7}
}

func (x *GetRoleByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoleByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Role          *Role                  `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                                // Retrieved role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleByIdResponse) Reset() {
	*x = GetRoleByIdResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleByIdResponse) ProtoMessage() {}

func (x *GetRoleByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleByIdResponse.ProtoReflect.Descriptor instead.
func (*GetRoleByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoleByIdResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetRoleByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRoleByIdResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // Role object with updated fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRoleRequest) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Role          *Role                  `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`                                // Updated role
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRoleResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Role ID (UUID as string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRoleResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteRoleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request messages for Permission CRUD operations
type CreatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Unique name
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // Optional description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequest) Reset() {
	*x = CreatePermissionRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequest) ProtoMessage() {}

func (x *CreatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequest.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePermissionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Permission    *Permission            `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`                    // Created permission
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponse) Reset() {
	*x = CreatePermissionResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponse) ProtoMessage() {}

func (x *CreatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponse.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePermissionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreatePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GetAllPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPermissionsRequest) Reset() {
	*x = GetAllPermissionsRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPermissionsRequest) ProtoMessage() {}

func (x *GetAllPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{15}
}

type GetAllPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Permissions   []*Permission          `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`                  // List of permissions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPermissionsResponse) Reset() {
	*x = GetAllPermissionsResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPermissionsResponse) ProtoMessage() {}

func (x *GetAllPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GetAllPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{16}
}

func (x *GetAllPermissionsResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAllPermissionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllPermissionsResponse) GetPermissions() []*Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GetPermissionByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Permission ID (UUID as string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionByIdRequest) Reset() {
	*x = GetPermissionByIdRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionByIdRequest) ProtoMessage() {}

func (x *GetPermissionByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPermissionByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{17}
}

func (x *GetPermissionByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPermissionByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Permission    *Permission            `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`                    // Retrieved permission
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionByIdResponse) Reset() {
	*x = GetPermissionByIdResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionByIdResponse) ProtoMessage() {}

func (x *GetPermissionByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPermissionByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{18}
}

func (x *GetPermissionByIdResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetPermissionByIdResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPermissionByIdResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permission    *Permission            `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"` // Permission object with updated fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequest) Reset() {
	*x = UpdatePermissionRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequest) ProtoMessage() {}

func (x *UpdatePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequest.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{19}
}

func (x *UpdatePermissionRequest) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type UpdatePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	Permission    *Permission            `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`                    // Updated permission
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponse) Reset() {
	*x = UpdatePermissionResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponse) ProtoMessage() {}

func (x *UpdatePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponse.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{20}
}

func (x *UpdatePermissionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdatePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePermissionResponse) GetPermission() *Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type DeletePermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // Permission ID (UUID as string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequest) Reset() {
	*x = DeletePermissionRequest{}
	mi := &file_proto_role_permission_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequest) ProtoMessage() {}

func (x *DeletePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequest.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{21}
}

func (x *DeletePermissionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status code equivalent
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                          // Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponse) Reset() {
	*x = DeletePermissionResponse{}
	mi := &file_proto_role_permission_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponse) ProtoMessage() {}

func (x *DeletePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponse.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_proto_rawDescGZIP(), []int{22}
}

func (x *DeletePermissionResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeletePermissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_role_permission_proto protoreflect.FileDescriptor

const file_proto_role_permission_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/role_permission.proto\x12\x0frole_permission\"T\n" +
	"\x04Base\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\"L\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"R\n" +
	"\n" +
	"Permission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"I\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"z\n" +
	"\x12CreateRoleResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04role\x18\x03 \x01(\v2\x15.role_permission.RoleR\x04role\"\x14\n" +
	"\x12GetAllRolesRequest\"}\n" +
	"\x13GetAllRolesResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x05roles\x18\x03 \x03(\v2\x15.role_permission.RoleR\x05roles\"$\n" +
	"\x12GetRoleByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"{\n" +
	"\x13GetRoleByIdResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04role\x18\x03 \x01(\v2\x15.role_permission.RoleR\x04role\">\n" +
	"\x11UpdateRoleRequest\x12)\n" +
	"\x04role\x18\x01 \x01(\v2\x15.role_permission.RoleR\x04role\"z\n" +
	"\x12UpdateRoleResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x04role\x18\x03 \x01(\v2\x15.role_permission.RoleR\x04role\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x12DeleteRoleResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x17CreatePermissionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\x92\x01\n" +
	"\x18CreatePermissionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2\x1b.role_permission.PermissionR\n" +
	"permission\"\x1a\n" +
	"\x18GetAllPermissionsRequest\"\x95\x01\n" +
	"\x19GetAllPermissionsResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\vpermissions\x18\x03 \x03(\v2\x1b.role_permission.PermissionR\vpermissions\"*\n" +
	"\x18GetPermissionByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x93\x01\n" +
	"\x19GetPermissionByIdResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2\x1b.role_permission.PermissionR\n" +
	"permission\"V\n" +
	"\x17UpdatePermissionRequest\x12;\n" +
	"\n" +
	"permission\x18\x01 \x01(\v2\x1b.role_permission.PermissionR\n" +
	"permission\"\x92\x01\n" +
	"\x18UpdatePermissionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2\x1b.role_permission.PermissionR\n" +
	"permission\")\n" +
	"\x17DeletePermissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x18DeletePermissionResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xc6\x03\n" +
	"\vRoleService\x12U\n" +
	"\n" +
	"CreateRole\x12\".role_permission.CreateRoleRequest\x1a#.role_permission.CreateRoleResponse\x12X\n" +
	"\vGetAllRoles\x12#.role_permission.GetAllRolesRequest\x1a$.role_permission.GetAllRolesResponse\x12X\n" +
	"\vGetRoleById\x12#.role_permission.GetRoleByIdRequest\x1a$.role_permission.GetRoleByIdResponse\x12U\n" +
	"\n" +
	"UpdateRole\x12\".role_permission.UpdateRoleRequest\x1a#.role_permission.UpdateRoleResponse\x12U\n" +
	"\n" +
	"DeleteRole\x12\".role_permission.DeleteRoleRequest\x1a#.role_permission.DeleteRoleResponse2\xa6\x04\n" +
	"\x11PermissionService\x12g\n" +
	"\x10CreatePermission\x12(.role_permission.CreatePermissionRequest\x1a).role_permission.CreatePermissionResponse\x12j\n" +
	"\x11GetAllPermissions\x12).role_permission.GetAllPermissionsRequest\x1a*.role_permission.GetAllPermissionsResponse\x12j\n" +
	"\x11GetPermissionById\x12).role_permission.GetPermissionByIdRequest\x1a*.role_permission.GetPermissionByIdResponse\x12g\n" +
	"\x10UpdatePermission\x12(.role_permission.UpdatePermissionRequest\x1a).role_permission.UpdatePermissionResponse\x12g\n" +
	"\x10DeletePermission\x12(.role_permission.DeletePermissionRequest\x1a).role_permission.DeletePermissionResponseB%Z#github.com/Kisanlink/aaa-service/pbb\x06proto3"

var (
	file_proto_role_permission_proto_rawDescOnce sync.Once
	file_proto_role_permission_proto_rawDescData []byte
)

func file_proto_role_permission_proto_rawDescGZIP() []byte {
	file_proto_role_permission_proto_rawDescOnce.Do(func() {
		file_proto_role_permission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_role_permission_proto_rawDesc), len(file_proto_role_permission_proto_rawDesc)))
	})
	return file_proto_role_permission_proto_rawDescData
}

var file_proto_role_permission_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_role_permission_proto_goTypes = []any{
	(*Base)(nil),                      // 0: role_permission.Base
	(*Role)(nil),                      // 1: role_permission.Role
	(*Permission)(nil),                // 2: role_permission.Permission
	(*CreateRoleRequest)(nil),         // 3: role_permission.CreateRoleRequest
	(*CreateRoleResponse)(nil),        // 4: role_permission.CreateRoleResponse
	(*GetAllRolesRequest)(nil),        // 5: role_permission.GetAllRolesRequest
	(*GetAllRolesResponse)(nil),       // 6: role_permission.GetAllRolesResponse
	(*GetRoleByIdRequest)(nil),        // 7: role_permission.GetRoleByIdRequest
	(*GetRoleByIdResponse)(nil),       // 8: role_permission.GetRoleByIdResponse
	(*UpdateRoleRequest)(nil),         // 9: role_permission.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),        // 10: role_permission.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),         // 11: role_permission.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),        // 12: role_permission.DeleteRoleResponse
	(*CreatePermissionRequest)(nil),   // 13: role_permission.CreatePermissionRequest
	(*CreatePermissionResponse)(nil),  // 14: role_permission.CreatePermissionResponse
	(*GetAllPermissionsRequest)(nil),  // 15: role_permission.GetAllPermissionsRequest
	(*GetAllPermissionsResponse)(nil), // 16: role_permission.GetAllPermissionsResponse
	(*GetPermissionByIdRequest)(nil),  // 17: role_permission.GetPermissionByIdRequest
	(*GetPermissionByIdResponse)(nil), // 18: role_permission.GetPermissionByIdResponse
	(*UpdatePermissionRequest)(nil),   // 19: role_permission.UpdatePermissionRequest
	(*UpdatePermissionResponse)(nil),  // 20: role_permission.UpdatePermissionResponse
	(*DeletePermissionRequest)(nil),   // 21: role_permission.DeletePermissionRequest
	(*DeletePermissionResponse)(nil),  // 22: role_permission.DeletePermissionResponse
}
var file_proto_role_permission_proto_depIdxs = []int32{
	1,  // 0: role_permission.CreateRoleResponse.role:type_name -> role_permission.Role
	1,  // 1: role_permission.GetAllRolesResponse.roles:type_name -> role_permission.Role
	1,  // 2: role_permission.GetRoleByIdResponse.role:type_name -> role_permission.Role
	1,  // 3: role_permission.UpdateRoleRequest.role:type_name -> role_permission.Role
	1,  // 4: role_permission.UpdateRoleResponse.role:type_name -> role_permission.Role
	2,  // 5: role_permission.CreatePermissionResponse.permission:type_name -> role_permission.Permission
	2,  // 6: role_permission.GetAllPermissionsResponse.permissions:type_name -> role_permission.Permission
	2,  // 7: role_permission.GetPermissionByIdResponse.permission:type_name -> role_permission.Permission
	2,  // 8: role_permission.UpdatePermissionRequest.permission:type_name -> role_permission.Permission
	2,  // 9: role_permission.UpdatePermissionResponse.permission:type_name -> role_permission.Permission
	3,  // 10: role_permission.RoleService.CreateRole:input_type -> role_permission.CreateRoleRequest
	5,  // 11: role_permission.RoleService.GetAllRoles:input_type -> role_permission.GetAllRolesRequest
	7,  // 12: role_permission.RoleService.GetRoleById:input_type -> role_permission.GetRoleByIdRequest
	9,  // 13: role_permission.RoleService.UpdateRole:input_type -> role_permission.UpdateRoleRequest
	11, // 14: role_permission.RoleService.DeleteRole:input_type -> role_permission.DeleteRoleRequest
	13, // 15: role_permission.PermissionService.CreatePermission:input_type -> role_permission.CreatePermissionRequest
	15, // 16: role_permission.PermissionService.GetAllPermissions:input_type -> role_permission.GetAllPermissionsRequest
	17, // 17: role_permission.PermissionService.GetPermissionById:input_type -> role_permission.GetPermissionByIdRequest
	19, // 18: role_permission.PermissionService.UpdatePermission:input_type -> role_permission.UpdatePermissionRequest
	21, // 19: role_permission.PermissionService.DeletePermission:input_type -> role_permission.DeletePermissionRequest
	4,  // 20: role_permission.RoleService.CreateRole:output_type -> role_permission.CreateRoleResponse
	6,  // 21: role_permission.RoleService.GetAllRoles:output_type -> role_permission.GetAllRolesResponse
	8,  // 22: role_permission.RoleService.GetRoleById:output_type -> role_permission.GetRoleByIdResponse
	10, // 23: role_permission.RoleService.UpdateRole:output_type -> role_permission.UpdateRoleResponse
	12, // 24: role_permission.RoleService.DeleteRole:output_type -> role_permission.DeleteRoleResponse
	14, // 25: role_permission.PermissionService.CreatePermission:output_type -> role_permission.CreatePermissionResponse
	16, // 26: role_permission.PermissionService.GetAllPermissions:output_type -> role_permission.GetAllPermissionsResponse
	18, // 27: role_permission.PermissionService.GetPermissionById:output_type -> role_permission.GetPermissionByIdResponse
	20, // 28: role_permission.PermissionService.UpdatePermission:output_type -> role_permission.UpdatePermissionResponse
	22, // 29: role_permission.PermissionService.DeletePermission:output_type -> role_permission.DeletePermissionResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_role_permission_proto_init() }
func file_proto_role_permission_proto_init() {
	if File_proto_role_permission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_permission_proto_rawDesc), len(file_proto_role_permission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_role_permission_proto_goTypes,
		DependencyIndexes: file_proto_role_permission_proto_depIdxs,
		MessageInfos:      file_proto_role_permission_proto_msgTypes,
	}.Build()
	File_proto_role_permission_proto = out.File
	file_proto_role_permission_proto_goTypes = nil
	file_proto_role_permission_proto_depIdxs = nil
}
