// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/role_permission_v2.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// V2 Role model with enhanced fields
type RoleV2 struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Permissions    []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	ChildRoles     []string               `protobuf:"bytes,8,rep,name=child_roles,json=childRoles,proto3" json:"child_roles,omitempty"`
	ParentRoleId   string                 `protobuf:"bytes,9,opt,name=parent_role_id,json=parentRoleId,proto3" json:"parent_role_id,omitempty"`
	HierarchyLevel int32                  `protobuf:"varint,10,opt,name=hierarchy_level,json=hierarchyLevel,proto3" json:"hierarchy_level,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoleV2) Reset() {
	*x = RoleV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleV2) ProtoMessage() {}

func (x *RoleV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleV2.ProtoReflect.Descriptor instead.
func (*RoleV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{0}
}

func (x *RoleV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoleV2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleV2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RoleV2) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RoleV2) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RoleV2) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *RoleV2) GetChildRoles() []string {
	if x != nil {
		return x.ChildRoles
	}
	return nil
}

func (x *RoleV2) GetParentRoleId() string {
	if x != nil {
		return x.ParentRoleId
	}
	return ""
}

func (x *RoleV2) GetHierarchyLevel() int32 {
	if x != nil {
		return x.HierarchyLevel
	}
	return 0
}

// V2 Permission model with enhanced fields
type PermissionV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Effect        string                 `protobuf:"bytes,5,opt,name=effect,proto3" json:"effect,omitempty"`
	Actions       []string               `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionV2) Reset() {
	*x = PermissionV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionV2) ProtoMessage() {}

func (x *PermissionV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionV2.ProtoReflect.Descriptor instead.
func (*PermissionV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PermissionV2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PermissionV2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PermissionV2) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionV2) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *PermissionV2) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *PermissionV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PermissionV2) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PermissionV2) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// V2 Role-Permission Connection model
type RolePermissionConnectionV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RoleId        string                 `protobuf:"bytes,2,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,3,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Role          *RoleV2                `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Permission    *PermissionV2          `protobuf:"bytes,7,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RolePermissionConnectionV2) Reset() {
	*x = RolePermissionConnectionV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RolePermissionConnectionV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RolePermissionConnectionV2) ProtoMessage() {}

func (x *RolePermissionConnectionV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RolePermissionConnectionV2.ProtoReflect.Descriptor instead.
func (*RolePermissionConnectionV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{2}
}

func (x *RolePermissionConnectionV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RolePermissionConnectionV2) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RolePermissionConnectionV2) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

func (x *RolePermissionConnectionV2) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RolePermissionConnectionV2) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RolePermissionConnectionV2) GetRole() *RoleV2 {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *RolePermissionConnectionV2) GetPermission() *PermissionV2 {
	if x != nil {
		return x.Permission
	}
	return nil
}

// V2 Create Role Request
type CreateRoleRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParentRoleId  string                 `protobuf:"bytes,3,opt,name=parent_role_id,json=parentRoleId,proto3" json:"parent_role_id,omitempty"`
	PermissionIds []string               `protobuf:"bytes,4,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequestV2) Reset() {
	*x = CreateRoleRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequestV2) ProtoMessage() {}

func (x *CreateRoleRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequestV2.ProtoReflect.Descriptor instead.
func (*CreateRoleRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoleRequestV2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequestV2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRoleRequestV2) GetParentRoleId() string {
	if x != nil {
		return x.ParentRoleId
	}
	return ""
}

func (x *CreateRoleRequestV2) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// V2 Create Role Response
type CreateRoleResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role          *RoleV2                `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponseV2) Reset() {
	*x = CreateRoleResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponseV2) ProtoMessage() {}

func (x *CreateRoleResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponseV2.ProtoReflect.Descriptor instead.
func (*CreateRoleResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreateRoleResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateRoleResponseV2) GetRole() *RoleV2 {
	if x != nil {
		return x.Role
	}
	return nil
}

// V2 Get Role Request
type GetRoleRequestV2 struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IncludePermissions bool                   `protobuf:"varint,2,opt,name=include_permissions,json=includePermissions,proto3" json:"include_permissions,omitempty"`
	IncludeChildRoles  bool                   `protobuf:"varint,3,opt,name=include_child_roles,json=includeChildRoles,proto3" json:"include_child_roles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetRoleRequestV2) Reset() {
	*x = GetRoleRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequestV2) ProtoMessage() {}

func (x *GetRoleRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequestV2.ProtoReflect.Descriptor instead.
func (*GetRoleRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoleRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetRoleRequestV2) GetIncludePermissions() bool {
	if x != nil {
		return x.IncludePermissions
	}
	return false
}

func (x *GetRoleRequestV2) GetIncludeChildRoles() bool {
	if x != nil {
		return x.IncludeChildRoles
	}
	return false
}

// V2 Get Role Response
type GetRoleResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role          *RoleV2                `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponseV2) Reset() {
	*x = GetRoleResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponseV2) ProtoMessage() {}

func (x *GetRoleResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponseV2.ProtoReflect.Descriptor instead.
func (*GetRoleResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoleResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetRoleResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRoleResponseV2) GetRole() *RoleV2 {
	if x != nil {
		return x.Role
	}
	return nil
}

// V2 Get All Roles Request
type GetAllRolesRequestV2 struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Page               int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage            int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search             string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ParentRoleId       string                 `protobuf:"bytes,5,opt,name=parent_role_id,json=parentRoleId,proto3" json:"parent_role_id,omitempty"`
	IncludePermissions bool                   `protobuf:"varint,6,opt,name=include_permissions,json=includePermissions,proto3" json:"include_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAllRolesRequestV2) Reset() {
	*x = GetAllRolesRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRolesRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRolesRequestV2) ProtoMessage() {}

func (x *GetAllRolesRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRolesRequestV2.ProtoReflect.Descriptor instead.
func (*GetAllRolesRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{7}
}

func (x *GetAllRolesRequestV2) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllRolesRequestV2) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAllRolesRequestV2) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllRolesRequestV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAllRolesRequestV2) GetParentRoleId() string {
	if x != nil {
		return x.ParentRoleId
	}
	return ""
}

func (x *GetAllRolesRequestV2) GetIncludePermissions() bool {
	if x != nil {
		return x.IncludePermissions
	}
	return false
}

// V2 Get All Roles Response
type GetAllRolesResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Roles         []*RoleV2              `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRolesResponseV2) Reset() {
	*x = GetAllRolesResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRolesResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRolesResponseV2) ProtoMessage() {}

func (x *GetAllRolesResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRolesResponseV2.ProtoReflect.Descriptor instead.
func (*GetAllRolesResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllRolesResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAllRolesResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllRolesResponseV2) GetRoles() []*RoleV2 {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *GetAllRolesResponseV2) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAllRolesResponseV2) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllRolesResponseV2) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// V2 Update Role Request
type UpdateRoleRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ParentRoleId  string                 `protobuf:"bytes,5,opt,name=parent_role_id,json=parentRoleId,proto3" json:"parent_role_id,omitempty"`
	PermissionIds []string               `protobuf:"bytes,6,rep,name=permission_ids,json=permissionIds,proto3" json:"permission_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequestV2) Reset() {
	*x = UpdateRoleRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequestV2) ProtoMessage() {}

func (x *UpdateRoleRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequestV2.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRoleRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequestV2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateRoleRequestV2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRoleRequestV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRoleRequestV2) GetParentRoleId() string {
	if x != nil {
		return x.ParentRoleId
	}
	return ""
}

func (x *UpdateRoleRequestV2) GetPermissionIds() []string {
	if x != nil {
		return x.PermissionIds
	}
	return nil
}

// V2 Update Role Response
type UpdateRoleResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Role          *RoleV2                `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponseV2) Reset() {
	*x = UpdateRoleResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponseV2) ProtoMessage() {}

func (x *UpdateRoleResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponseV2.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRoleResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateRoleResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateRoleResponseV2) GetRole() *RoleV2 {
	if x != nil {
		return x.Role
	}
	return nil
}

// V2 Delete Role Request
type DeleteRoleRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cascade       bool                   `protobuf:"varint,2,opt,name=cascade,proto3" json:"cascade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequestV2) Reset() {
	*x = DeleteRoleRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequestV2) ProtoMessage() {}

func (x *DeleteRoleRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequestV2.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRoleRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRoleRequestV2) GetCascade() bool {
	if x != nil {
		return x.Cascade
	}
	return false
}

// V2 Delete Role Response
type DeleteRoleResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponseV2) Reset() {
	*x = DeleteRoleResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponseV2) ProtoMessage() {}

func (x *DeleteRoleResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponseV2.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRoleResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeleteRoleResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// V2 Create Permission Request
type CreatePermissionRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Effect        string                 `protobuf:"bytes,4,opt,name=effect,proto3" json:"effect,omitempty"`
	Actions       []string               `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionRequestV2) Reset() {
	*x = CreatePermissionRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionRequestV2) ProtoMessage() {}

func (x *CreatePermissionRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionRequestV2.ProtoReflect.Descriptor instead.
func (*CreatePermissionRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePermissionRequestV2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePermissionRequestV2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePermissionRequestV2) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreatePermissionRequestV2) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *CreatePermissionRequestV2) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

// V2 Create Permission Response
type CreatePermissionResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Permission    *PermissionV2          `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePermissionResponseV2) Reset() {
	*x = CreatePermissionResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePermissionResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePermissionResponseV2) ProtoMessage() {}

func (x *CreatePermissionResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePermissionResponseV2.ProtoReflect.Descriptor instead.
func (*CreatePermissionResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePermissionResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CreatePermissionResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreatePermissionResponseV2) GetPermission() *PermissionV2 {
	if x != nil {
		return x.Permission
	}
	return nil
}

// V2 Get Permission Request
type GetPermissionRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionRequestV2) Reset() {
	*x = GetPermissionRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionRequestV2) ProtoMessage() {}

func (x *GetPermissionRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionRequestV2.ProtoReflect.Descriptor instead.
func (*GetPermissionRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{15}
}

func (x *GetPermissionRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// V2 Get Permission Response
type GetPermissionResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Permission    *PermissionV2          `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPermissionResponseV2) Reset() {
	*x = GetPermissionResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPermissionResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionResponseV2) ProtoMessage() {}

func (x *GetPermissionResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionResponseV2.ProtoReflect.Descriptor instead.
func (*GetPermissionResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{16}
}

func (x *GetPermissionResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetPermissionResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPermissionResponseV2) GetPermission() *PermissionV2 {
	if x != nil {
		return x.Permission
	}
	return nil
}

// V2 Get All Permissions Request
type GetAllPermissionsRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Effect        string                 `protobuf:"bytes,5,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPermissionsRequestV2) Reset() {
	*x = GetAllPermissionsRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPermissionsRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPermissionsRequestV2) ProtoMessage() {}

func (x *GetAllPermissionsRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPermissionsRequestV2.ProtoReflect.Descriptor instead.
func (*GetAllPermissionsRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{17}
}

func (x *GetAllPermissionsRequestV2) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllPermissionsRequestV2) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetAllPermissionsRequestV2) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetAllPermissionsRequestV2) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *GetAllPermissionsRequestV2) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

// V2 Get All Permissions Response
type GetAllPermissionsResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Permissions   []*PermissionV2        `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,6,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPermissionsResponseV2) Reset() {
	*x = GetAllPermissionsResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPermissionsResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPermissionsResponseV2) ProtoMessage() {}

func (x *GetAllPermissionsResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPermissionsResponseV2.ProtoReflect.Descriptor instead.
func (*GetAllPermissionsResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{18}
}

func (x *GetAllPermissionsResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetAllPermissionsResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAllPermissionsResponseV2) GetPermissions() []*PermissionV2 {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GetAllPermissionsResponseV2) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAllPermissionsResponseV2) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllPermissionsResponseV2) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// V2 Update Permission Request
type UpdatePermissionRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Effect        string                 `protobuf:"bytes,5,opt,name=effect,proto3" json:"effect,omitempty"`
	Actions       []string               `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionRequestV2) Reset() {
	*x = UpdatePermissionRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionRequestV2) ProtoMessage() {}

func (x *UpdatePermissionRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionRequestV2.ProtoReflect.Descriptor instead.
func (*UpdatePermissionRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{19}
}

func (x *UpdatePermissionRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePermissionRequestV2) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePermissionRequestV2) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdatePermissionRequestV2) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *UpdatePermissionRequestV2) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

func (x *UpdatePermissionRequestV2) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *UpdatePermissionRequestV2) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// V2 Update Permission Response
type UpdatePermissionResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Permission    *PermissionV2          `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePermissionResponseV2) Reset() {
	*x = UpdatePermissionResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePermissionResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePermissionResponseV2) ProtoMessage() {}

func (x *UpdatePermissionResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePermissionResponseV2.ProtoReflect.Descriptor instead.
func (*UpdatePermissionResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{20}
}

func (x *UpdatePermissionResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdatePermissionResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePermissionResponseV2) GetPermission() *PermissionV2 {
	if x != nil {
		return x.Permission
	}
	return nil
}

// V2 Delete Permission Request
type DeletePermissionRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionRequestV2) Reset() {
	*x = DeletePermissionRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionRequestV2) ProtoMessage() {}

func (x *DeletePermissionRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionRequestV2.ProtoReflect.Descriptor instead.
func (*DeletePermissionRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{21}
}

func (x *DeletePermissionRequestV2) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// V2 Delete Permission Response
type DeletePermissionResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePermissionResponseV2) Reset() {
	*x = DeletePermissionResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePermissionResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePermissionResponseV2) ProtoMessage() {}

func (x *DeletePermissionResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePermissionResponseV2.ProtoReflect.Descriptor instead.
func (*DeletePermissionResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{22}
}

func (x *DeletePermissionResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *DeletePermissionResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// V2 Assign Permission to Role Request
type AssignPermissionToRoleRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionToRoleRequestV2) Reset() {
	*x = AssignPermissionToRoleRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionToRoleRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionToRoleRequestV2) ProtoMessage() {}

func (x *AssignPermissionToRoleRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionToRoleRequestV2.ProtoReflect.Descriptor instead.
func (*AssignPermissionToRoleRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{23}
}

func (x *AssignPermissionToRoleRequestV2) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *AssignPermissionToRoleRequestV2) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

// V2 Assign Permission to Role Response
type AssignPermissionToRoleResponseV2 struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	StatusCode    int32                       `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Connection    *RolePermissionConnectionV2 `protobuf:"bytes,3,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPermissionToRoleResponseV2) Reset() {
	*x = AssignPermissionToRoleResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPermissionToRoleResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPermissionToRoleResponseV2) ProtoMessage() {}

func (x *AssignPermissionToRoleResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPermissionToRoleResponseV2.ProtoReflect.Descriptor instead.
func (*AssignPermissionToRoleResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{24}
}

func (x *AssignPermissionToRoleResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AssignPermissionToRoleResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssignPermissionToRoleResponseV2) GetConnection() *RolePermissionConnectionV2 {
	if x != nil {
		return x.Connection
	}
	return nil
}

// V2 Remove Permission from Role Request
type RemovePermissionFromRoleRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	PermissionId  string                 `protobuf:"bytes,2,opt,name=permission_id,json=permissionId,proto3" json:"permission_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePermissionFromRoleRequestV2) Reset() {
	*x = RemovePermissionFromRoleRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePermissionFromRoleRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermissionFromRoleRequestV2) ProtoMessage() {}

func (x *RemovePermissionFromRoleRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermissionFromRoleRequestV2.ProtoReflect.Descriptor instead.
func (*RemovePermissionFromRoleRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{25}
}

func (x *RemovePermissionFromRoleRequestV2) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RemovePermissionFromRoleRequestV2) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

// V2 Remove Permission from Role Response
type RemovePermissionFromRoleResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePermissionFromRoleResponseV2) Reset() {
	*x = RemovePermissionFromRoleResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePermissionFromRoleResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePermissionFromRoleResponseV2) ProtoMessage() {}

func (x *RemovePermissionFromRoleResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePermissionFromRoleResponseV2.ProtoReflect.Descriptor instead.
func (*RemovePermissionFromRoleResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{26}
}

func (x *RemovePermissionFromRoleResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RemovePermissionFromRoleResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// V2 Get Role Permissions Request
type GetRolePermissionsRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsRequestV2) Reset() {
	*x = GetRolePermissionsRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsRequestV2) ProtoMessage() {}

func (x *GetRolePermissionsRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsRequestV2.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{27}
}

func (x *GetRolePermissionsRequestV2) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

// V2 Get Role Permissions Response
type GetRolePermissionsResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Permissions   []*PermissionV2        `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolePermissionsResponseV2) Reset() {
	*x = GetRolePermissionsResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolePermissionsResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolePermissionsResponseV2) ProtoMessage() {}

func (x *GetRolePermissionsResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolePermissionsResponseV2.ProtoReflect.Descriptor instead.
func (*GetRolePermissionsResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{28}
}

func (x *GetRolePermissionsResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetRolePermissionsResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRolePermissionsResponseV2) GetPermissions() []*PermissionV2 {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// V2 Evaluate Permission Request
type EvaluatePermissionRequestV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Resource      string                 `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePermissionRequestV2) Reset() {
	*x = EvaluatePermissionRequestV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePermissionRequestV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePermissionRequestV2) ProtoMessage() {}

func (x *EvaluatePermissionRequestV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePermissionRequestV2.ProtoReflect.Descriptor instead.
func (*EvaluatePermissionRequestV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{29}
}

func (x *EvaluatePermissionRequestV2) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluatePermissionRequestV2) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *EvaluatePermissionRequestV2) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// V2 Evaluate Permission Response
type EvaluatePermissionResponseV2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Allowed       bool                   `protobuf:"varint,3,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Permissions   []string               `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePermissionResponseV2) Reset() {
	*x = EvaluatePermissionResponseV2{}
	mi := &file_proto_role_permission_v2_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePermissionResponseV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePermissionResponseV2) ProtoMessage() {}

func (x *EvaluatePermissionResponseV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_role_permission_v2_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePermissionResponseV2.ProtoReflect.Descriptor instead.
func (*EvaluatePermissionResponseV2) Descriptor() ([]byte, []int) {
	return file_proto_role_permission_v2_proto_rawDescGZIP(), []int{30}
}

func (x *EvaluatePermissionResponseV2) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *EvaluatePermissionResponseV2) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EvaluatePermissionResponseV2) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *EvaluatePermissionResponseV2) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_proto_role_permission_v2_proto protoreflect.FileDescriptor

const file_proto_role_permission_v2_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/role_permission_v2.proto\x12\x12role_permission_v2\"\xb6\x02\n" +
	"\x06RoleV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\x12\x1f\n" +
	"\vchild_roles\x18\b \x03(\tR\n" +
	"childRoles\x12$\n" +
	"\x0eparent_role_id\x18\t \x01(\tR\fparentRoleId\x12'\n" +
	"\x0fhierarchy_level\x18\n" +
	" \x01(\x05R\x0ehierarchyLevel\"\xf8\x01\n" +
	"\fPermissionV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\tR\x06effect\x12\x18\n" +
	"\aactions\x18\x06 \x03(\tR\aactions\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\x9a\x02\n" +
	"\x1aRolePermissionConnectionV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\arole_id\x18\x02 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x03 \x01(\tR\fpermissionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12.\n" +
	"\x04role\x18\x06 \x01(\v2\x1a.role_permission_v2.RoleV2R\x04role\x12@\n" +
	"\n" +
	"permission\x18\a \x01(\v2 .role_permission_v2.PermissionV2R\n" +
	"permission\"\x98\x01\n" +
	"\x13CreateRoleRequestV2\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12$\n" +
	"\x0eparent_role_id\x18\x03 \x01(\tR\fparentRoleId\x12%\n" +
	"\x0epermission_ids\x18\x04 \x03(\tR\rpermissionIds\"\x81\x01\n" +
	"\x14CreateRoleResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04role\x18\x03 \x01(\v2\x1a.role_permission_v2.RoleV2R\x04role\"\x83\x01\n" +
	"\x10GetRoleRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\x13include_permissions\x18\x02 \x01(\bR\x12includePermissions\x12.\n" +
	"\x13include_child_roles\x18\x03 \x01(\bR\x11includeChildRoles\"~\n" +
	"\x11GetRoleResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04role\x18\x03 \x01(\v2\x1a.role_permission_v2.RoleV2R\x04role\"\xcc\x01\n" +
	"\x14GetAllRolesRequestV2\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12$\n" +
	"\x0eparent_role_id\x18\x05 \x01(\tR\fparentRoleId\x12/\n" +
	"\x13include_permissions\x18\x06 \x01(\bR\x12includePermissions\"\xd4\x01\n" +
	"\x15GetAllRolesResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x05roles\x18\x03 \x03(\v2\x1a.role_permission_v2.RoleV2R\x05roles\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x06 \x01(\x05R\aperPage\"\xc0\x01\n" +
	"\x13UpdateRoleRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12$\n" +
	"\x0eparent_role_id\x18\x05 \x01(\tR\fparentRoleId\x12%\n" +
	"\x0epermission_ids\x18\x06 \x03(\tR\rpermissionIds\"\x81\x01\n" +
	"\x14UpdateRoleResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x04role\x18\x03 \x01(\v2\x1a.role_permission_v2.RoleV2R\x04role\"?\n" +
	"\x13DeleteRoleRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acascade\x18\x02 \x01(\bR\acascade\"Q\n" +
	"\x14DeleteRoleResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9f\x01\n" +
	"\x19CreatePermissionRequestV2\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06effect\x18\x04 \x01(\tR\x06effect\x12\x18\n" +
	"\aactions\x18\x05 \x03(\tR\aactions\"\x99\x01\n" +
	"\x1aCreatePermissionResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2 .role_permission_v2.PermissionV2R\n" +
	"permission\"(\n" +
	"\x16GetPermissionRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x96\x01\n" +
	"\x17GetPermissionResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2 .role_permission_v2.PermissionV2R\n" +
	"permission\"\x97\x01\n" +
	"\x1aGetAllPermissionsRequestV2\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\tR\x06effect\"\xec\x01\n" +
	"\x1bGetAllPermissionsResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\vpermissions\x18\x03 \x03(\v2 .role_permission_v2.PermissionV2R\vpermissions\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x06 \x01(\x05R\aperPage\"\xc7\x01\n" +
	"\x19UpdatePermissionRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06effect\x18\x05 \x01(\tR\x06effect\x12\x18\n" +
	"\aactions\x18\x06 \x03(\tR\aactions\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"\x99\x01\n" +
	"\x1aUpdatePermissionResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12@\n" +
	"\n" +
	"permission\x18\x03 \x01(\v2 .role_permission_v2.PermissionV2R\n" +
	"permission\"+\n" +
	"\x19DeletePermissionRequestV2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"W\n" +
	"\x1aDeletePermissionResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x1fAssignPermissionToRoleRequestV2\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\"\xad\x01\n" +
	" AssignPermissionToRoleResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12N\n" +
	"\n" +
	"connection\x18\x03 \x01(\v2..role_permission_v2.RolePermissionConnectionV2R\n" +
	"connection\"a\n" +
	"!RemovePermissionFromRoleRequestV2\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12#\n" +
	"\rpermission_id\x18\x02 \x01(\tR\fpermissionId\"_\n" +
	"\"RemovePermissionFromRoleResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"6\n" +
	"\x1bGetRolePermissionsRequestV2\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\"\x9d\x01\n" +
	"\x1cGetRolePermissionsResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\vpermissions\x18\x03 \x03(\v2 .role_permission_v2.PermissionV2R\vpermissions\"j\n" +
	"\x1bEvaluatePermissionRequestV2\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\x95\x01\n" +
	"\x1cEvaluatePermissionResponseV2\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aallowed\x18\x03 \x01(\bR\aallowed\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions2\xf9\x06\n" +
	"\rRoleServiceV2\x12_\n" +
	"\n" +
	"CreateRole\x12'.role_permission_v2.CreateRoleRequestV2\x1a(.role_permission_v2.CreateRoleResponseV2\x12V\n" +
	"\aGetRole\x12$.role_permission_v2.GetRoleRequestV2\x1a%.role_permission_v2.GetRoleResponseV2\x12b\n" +
	"\vGetAllRoles\x12(.role_permission_v2.GetAllRolesRequestV2\x1a).role_permission_v2.GetAllRolesResponseV2\x12_\n" +
	"\n" +
	"UpdateRole\x12'.role_permission_v2.UpdateRoleRequestV2\x1a(.role_permission_v2.UpdateRoleResponseV2\x12_\n" +
	"\n" +
	"DeleteRole\x12'.role_permission_v2.DeleteRoleRequestV2\x1a(.role_permission_v2.DeleteRoleResponseV2\x12\x83\x01\n" +
	"\x16AssignPermissionToRole\x123.role_permission_v2.AssignPermissionToRoleRequestV2\x1a4.role_permission_v2.AssignPermissionToRoleResponseV2\x12\x89\x01\n" +
	"\x18RemovePermissionFromRole\x125.role_permission_v2.RemovePermissionFromRoleRequestV2\x1a6.role_permission_v2.RemovePermissionFromRoleResponseV2\x12w\n" +
	"\x12GetRolePermissions\x12/.role_permission_v2.GetRolePermissionsRequestV2\x1a0.role_permission_v2.GetRolePermissionsResponseV22\xc7\x05\n" +
	"\x13PermissionServiceV2\x12q\n" +
	"\x10CreatePermission\x12-.role_permission_v2.CreatePermissionRequestV2\x1a..role_permission_v2.CreatePermissionResponseV2\x12h\n" +
	"\rGetPermission\x12*.role_permission_v2.GetPermissionRequestV2\x1a+.role_permission_v2.GetPermissionResponseV2\x12t\n" +
	"\x11GetAllPermissions\x12..role_permission_v2.GetAllPermissionsRequestV2\x1a/.role_permission_v2.GetAllPermissionsResponseV2\x12q\n" +
	"\x10UpdatePermission\x12-.role_permission_v2.UpdatePermissionRequestV2\x1a..role_permission_v2.UpdatePermissionResponseV2\x12q\n" +
	"\x10DeletePermission\x12-.role_permission_v2.DeletePermissionRequestV2\x1a..role_permission_v2.DeletePermissionResponseV2\x12w\n" +
	"\x12EvaluatePermission\x12/.role_permission_v2.EvaluatePermissionRequestV2\x1a0.role_permission_v2.EvaluatePermissionResponseV2B%Z#github.com/Kisanlink/aaa-service/pbb\x06proto3"

var (
	file_proto_role_permission_v2_proto_rawDescOnce sync.Once
	file_proto_role_permission_v2_proto_rawDescData []byte
)

func file_proto_role_permission_v2_proto_rawDescGZIP() []byte {
	file_proto_role_permission_v2_proto_rawDescOnce.Do(func() {
		file_proto_role_permission_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_role_permission_v2_proto_rawDesc), len(file_proto_role_permission_v2_proto_rawDesc)))
	})
	return file_proto_role_permission_v2_proto_rawDescData
}

var file_proto_role_permission_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_role_permission_v2_proto_goTypes = []any{
	(*RoleV2)(nil),                             // 0: role_permission_v2.RoleV2
	(*PermissionV2)(nil),                       // 1: role_permission_v2.PermissionV2
	(*RolePermissionConnectionV2)(nil),         // 2: role_permission_v2.RolePermissionConnectionV2
	(*CreateRoleRequestV2)(nil),                // 3: role_permission_v2.CreateRoleRequestV2
	(*CreateRoleResponseV2)(nil),               // 4: role_permission_v2.CreateRoleResponseV2
	(*GetRoleRequestV2)(nil),                   // 5: role_permission_v2.GetRoleRequestV2
	(*GetRoleResponseV2)(nil),                  // 6: role_permission_v2.GetRoleResponseV2
	(*GetAllRolesRequestV2)(nil),               // 7: role_permission_v2.GetAllRolesRequestV2
	(*GetAllRolesResponseV2)(nil),              // 8: role_permission_v2.GetAllRolesResponseV2
	(*UpdateRoleRequestV2)(nil),                // 9: role_permission_v2.UpdateRoleRequestV2
	(*UpdateRoleResponseV2)(nil),               // 10: role_permission_v2.UpdateRoleResponseV2
	(*DeleteRoleRequestV2)(nil),                // 11: role_permission_v2.DeleteRoleRequestV2
	(*DeleteRoleResponseV2)(nil),               // 12: role_permission_v2.DeleteRoleResponseV2
	(*CreatePermissionRequestV2)(nil),          // 13: role_permission_v2.CreatePermissionRequestV2
	(*CreatePermissionResponseV2)(nil),         // 14: role_permission_v2.CreatePermissionResponseV2
	(*GetPermissionRequestV2)(nil),             // 15: role_permission_v2.GetPermissionRequestV2
	(*GetPermissionResponseV2)(nil),            // 16: role_permission_v2.GetPermissionResponseV2
	(*GetAllPermissionsRequestV2)(nil),         // 17: role_permission_v2.GetAllPermissionsRequestV2
	(*GetAllPermissionsResponseV2)(nil),        // 18: role_permission_v2.GetAllPermissionsResponseV2
	(*UpdatePermissionRequestV2)(nil),          // 19: role_permission_v2.UpdatePermissionRequestV2
	(*UpdatePermissionResponseV2)(nil),         // 20: role_permission_v2.UpdatePermissionResponseV2
	(*DeletePermissionRequestV2)(nil),          // 21: role_permission_v2.DeletePermissionRequestV2
	(*DeletePermissionResponseV2)(nil),         // 22: role_permission_v2.DeletePermissionResponseV2
	(*AssignPermissionToRoleRequestV2)(nil),    // 23: role_permission_v2.AssignPermissionToRoleRequestV2
	(*AssignPermissionToRoleResponseV2)(nil),   // 24: role_permission_v2.AssignPermissionToRoleResponseV2
	(*RemovePermissionFromRoleRequestV2)(nil),  // 25: role_permission_v2.RemovePermissionFromRoleRequestV2
	(*RemovePermissionFromRoleResponseV2)(nil), // 26: role_permission_v2.RemovePermissionFromRoleResponseV2
	(*GetRolePermissionsRequestV2)(nil),        // 27: role_permission_v2.GetRolePermissionsRequestV2
	(*GetRolePermissionsResponseV2)(nil),       // 28: role_permission_v2.GetRolePermissionsResponseV2
	(*EvaluatePermissionRequestV2)(nil),        // 29: role_permission_v2.EvaluatePermissionRequestV2
	(*EvaluatePermissionResponseV2)(nil),       // 30: role_permission_v2.EvaluatePermissionResponseV2
}
var file_proto_role_permission_v2_proto_depIdxs = []int32{
	0,  // 0: role_permission_v2.RolePermissionConnectionV2.role:type_name -> role_permission_v2.RoleV2
	1,  // 1: role_permission_v2.RolePermissionConnectionV2.permission:type_name -> role_permission_v2.PermissionV2
	0,  // 2: role_permission_v2.CreateRoleResponseV2.role:type_name -> role_permission_v2.RoleV2
	0,  // 3: role_permission_v2.GetRoleResponseV2.role:type_name -> role_permission_v2.RoleV2
	0,  // 4: role_permission_v2.GetAllRolesResponseV2.roles:type_name -> role_permission_v2.RoleV2
	0,  // 5: role_permission_v2.UpdateRoleResponseV2.role:type_name -> role_permission_v2.RoleV2
	1,  // 6: role_permission_v2.CreatePermissionResponseV2.permission:type_name -> role_permission_v2.PermissionV2
	1,  // 7: role_permission_v2.GetPermissionResponseV2.permission:type_name -> role_permission_v2.PermissionV2
	1,  // 8: role_permission_v2.GetAllPermissionsResponseV2.permissions:type_name -> role_permission_v2.PermissionV2
	1,  // 9: role_permission_v2.UpdatePermissionResponseV2.permission:type_name -> role_permission_v2.PermissionV2
	2,  // 10: role_permission_v2.AssignPermissionToRoleResponseV2.connection:type_name -> role_permission_v2.RolePermissionConnectionV2
	1,  // 11: role_permission_v2.GetRolePermissionsResponseV2.permissions:type_name -> role_permission_v2.PermissionV2
	3,  // 12: role_permission_v2.RoleServiceV2.CreateRole:input_type -> role_permission_v2.CreateRoleRequestV2
	5,  // 13: role_permission_v2.RoleServiceV2.GetRole:input_type -> role_permission_v2.GetRoleRequestV2
	7,  // 14: role_permission_v2.RoleServiceV2.GetAllRoles:input_type -> role_permission_v2.GetAllRolesRequestV2
	9,  // 15: role_permission_v2.RoleServiceV2.UpdateRole:input_type -> role_permission_v2.UpdateRoleRequestV2
	11, // 16: role_permission_v2.RoleServiceV2.DeleteRole:input_type -> role_permission_v2.DeleteRoleRequestV2
	23, // 17: role_permission_v2.RoleServiceV2.AssignPermissionToRole:input_type -> role_permission_v2.AssignPermissionToRoleRequestV2
	25, // 18: role_permission_v2.RoleServiceV2.RemovePermissionFromRole:input_type -> role_permission_v2.RemovePermissionFromRoleRequestV2
	27, // 19: role_permission_v2.RoleServiceV2.GetRolePermissions:input_type -> role_permission_v2.GetRolePermissionsRequestV2
	13, // 20: role_permission_v2.PermissionServiceV2.CreatePermission:input_type -> role_permission_v2.CreatePermissionRequestV2
	15, // 21: role_permission_v2.PermissionServiceV2.GetPermission:input_type -> role_permission_v2.GetPermissionRequestV2
	17, // 22: role_permission_v2.PermissionServiceV2.GetAllPermissions:input_type -> role_permission_v2.GetAllPermissionsRequestV2
	19, // 23: role_permission_v2.PermissionServiceV2.UpdatePermission:input_type -> role_permission_v2.UpdatePermissionRequestV2
	21, // 24: role_permission_v2.PermissionServiceV2.DeletePermission:input_type -> role_permission_v2.DeletePermissionRequestV2
	29, // 25: role_permission_v2.PermissionServiceV2.EvaluatePermission:input_type -> role_permission_v2.EvaluatePermissionRequestV2
	4,  // 26: role_permission_v2.RoleServiceV2.CreateRole:output_type -> role_permission_v2.CreateRoleResponseV2
	6,  // 27: role_permission_v2.RoleServiceV2.GetRole:output_type -> role_permission_v2.GetRoleResponseV2
	8,  // 28: role_permission_v2.RoleServiceV2.GetAllRoles:output_type -> role_permission_v2.GetAllRolesResponseV2
	10, // 29: role_permission_v2.RoleServiceV2.UpdateRole:output_type -> role_permission_v2.UpdateRoleResponseV2
	12, // 30: role_permission_v2.RoleServiceV2.DeleteRole:output_type -> role_permission_v2.DeleteRoleResponseV2
	24, // 31: role_permission_v2.RoleServiceV2.AssignPermissionToRole:output_type -> role_permission_v2.AssignPermissionToRoleResponseV2
	26, // 32: role_permission_v2.RoleServiceV2.RemovePermissionFromRole:output_type -> role_permission_v2.RemovePermissionFromRoleResponseV2
	28, // 33: role_permission_v2.RoleServiceV2.GetRolePermissions:output_type -> role_permission_v2.GetRolePermissionsResponseV2
	14, // 34: role_permission_v2.PermissionServiceV2.CreatePermission:output_type -> role_permission_v2.CreatePermissionResponseV2
	16, // 35: role_permission_v2.PermissionServiceV2.GetPermission:output_type -> role_permission_v2.GetPermissionResponseV2
	18, // 36: role_permission_v2.PermissionServiceV2.GetAllPermissions:output_type -> role_permission_v2.GetAllPermissionsResponseV2
	20, // 37: role_permission_v2.PermissionServiceV2.UpdatePermission:output_type -> role_permission_v2.UpdatePermissionResponseV2
	22, // 38: role_permission_v2.PermissionServiceV2.DeletePermission:output_type -> role_permission_v2.DeletePermissionResponseV2
	30, // 39: role_permission_v2.PermissionServiceV2.EvaluatePermission:output_type -> role_permission_v2.EvaluatePermissionResponseV2
	26, // [26:40] is the sub-list for method output_type
	12, // [12:26] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_role_permission_v2_proto_init() }
func file_proto_role_permission_v2_proto_init() {
	if File_proto_role_permission_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_role_permission_v2_proto_rawDesc), len(file_proto_role_permission_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_role_permission_v2_proto_goTypes,
		DependencyIndexes: file_proto_role_permission_v2_proto_depIdxs,
		MessageInfos:      file_proto_role_permission_v2_proto_msgTypes,
	}.Build()
	File_proto_role_permission_v2_proto = out.File
	file_proto_role_permission_v2_proto_goTypes = nil
	file_proto_role_permission_v2_proto_depIdxs = nil
}
