// Code generated by mockery. DO NOT EDIT.

package mocks

import (
    context "context"

    catalog "kisanlink-ecom/entities/models/catalog"
    requests "kisanlink-ecom/entities/requests/catalog"

    mock "github.com/stretchr/testify/mock"
)

// CatalogServiceInterface is an autogenerated mock type for the CatalogServiceInterface type
type CatalogServiceInterface struct {
    mock.Mock
}

// CreateLabour provides a mock function with given fields: ctx, req, userID
func (_m *CatalogServiceInterface) CreateLabour(ctx context.Context, req *requests.CreateLabourRequest, userID string) (*catalog.Labour, error) {
    ret := _m.Called(ctx, req, userID)

    var r0 *catalog.Labour
    if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateLabourRequest, string) *catalog.Labour); ok {
        r0 = rf(ctx, req, userID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Labour)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, *requests.CreateLabourRequest, string) error); ok {
        r1 = rf(ctx, req, userID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// CreateProduct provides a mock function with given fields: ctx, product, userID
func (_m *CatalogServiceInterface) CreateProduct(ctx context.Context, product *catalog.Product, userID string) (*catalog.Product, error) {
    ret := _m.Called(ctx, product, userID)

    var r0 *catalog.Product
    if rf, ok := ret.Get(0).(func(context.Context, *catalog.Product, string) *catalog.Product); ok {
        r0 = rf(ctx, product, userID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Product)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, *catalog.Product, string) error); ok {
        r1 = rf(ctx, product, userID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// CreateService provides a mock function with given fields: ctx, req, userID
func (_m *CatalogServiceInterface) CreateService(ctx context.Context, req *requests.CreateServiceRequest, userID string) (*catalog.Service, error) {
    ret := _m.Called(ctx, req, userID)

    var r0 *catalog.Service
    if rf, ok := ret.Get(0).(func(context.Context, *requests.CreateServiceRequest, string) *catalog.Service); ok {
        r0 = rf(ctx, req, userID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Service)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, *requests.CreateServiceRequest, string) error); ok {
        r1 = rf(ctx, req, userID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// DeleteLabour provides a mock function with given fields: ctx, labourID, userID
func (_m *CatalogServiceInterface) DeleteLabour(ctx context.Context, labourID string, userID string) error {
    ret := _m.Called(ctx, labourID, userID)

    var r0 error
    if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
        r0 = rf(ctx, labourID, userID)
    } else {
        r0 = ret.Error(0)
    }

    return r0
}

// DeleteProduct provides a mock function with given fields: ctx, productID, userID
func (_m *CatalogServiceInterface) DeleteProduct(ctx context.Context, productID string, userID string) error {
    ret := _m.Called(ctx, productID, userID)

    var r0 error
    if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
        r0 = rf(ctx, productID, userID)
    } else {
        r0 = ret.Error(0)
    }

    return r0
}

// DeleteService provides a mock function with given fields: ctx, serviceID, userID
func (_m *CatalogServiceInterface) DeleteService(ctx context.Context, serviceID string, userID string) error {
    ret := _m.Called(ctx, serviceID, userID)

    var r0 error
    if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
        r0 = rf(ctx, serviceID, userID)
    } else {
        r0 = ret.Error(0)
    }

    return r0
}

// GetCatalogItemByID provides a mock function with given fields: ctx, id
func (_m *CatalogServiceInterface) GetCatalogItemByID(ctx context.Context, id string) (*catalog.CatalogItem, error) {
    ret := _m.Called(ctx, id)

    var r0 *catalog.CatalogItem
    if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.CatalogItem); ok {
        r0 = rf(ctx, id)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.CatalogItem)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, id)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// GetInventoryLevel provides a mock function with given fields: ctx, itemID
func (_m *CatalogServiceInterface) GetInventoryLevel(ctx context.Context, itemID string) (float64, error) {
    ret := _m.Called(ctx, itemID)

    var r0 float64
    if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
        r0 = rf(ctx, itemID)
    } else {
        r0 = ret.Get(0).(float64)
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, itemID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// GetLabourByID provides a mock function with given fields: ctx, labourID
func (_m *CatalogServiceInterface) GetLabourByID(ctx context.Context, labourID string) (*catalog.Labour, error) {
    ret := _m.Called(ctx, labourID)

    var r0 *catalog.Labour
    if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.Labour); ok {
        r0 = rf(ctx, labourID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Labour)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, labourID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// GetLabourBySKU provides a mock function with given fields: ctx, sku
func (_m *CatalogServiceInterface) GetLabourBySKU(ctx context.Context, sku string) (*catalog.Labour, error) {
    ret := _m.Called(ctx, sku)

    var r0 *catalog.Labour
    if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.Labour); ok {
        r0 = rf(ctx, sku)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Labour)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, sku)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, productID
func (_m *CatalogServiceInterface) GetProductByID(ctx context.Context, productID string) (*catalog.Product, error) {
    ret := _m.Called(ctx, productID)

    var r0 *catalog.Product
    if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.Product); ok {
        r0 = rf(ctx, productID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Product)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, productID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// GetProductBySKU provides a mock function with given fields: ctx, sku
func (_m *CatalogServiceInterface) GetProductBySKU(ctx context.Context, sku string) (*catalog.Product, error) {
    ret := _m.Called(ctx, sku)

    var r0 *catalog.Product
    if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.Product); ok {
        r0 = rf(ctx, sku)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Product)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, sku)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// GetServiceByID provides a mock function with given fields: ctx, serviceID
func (_m *CatalogServiceInterface) GetServiceByID(ctx context.Context, serviceID string) (*catalog.Service, error) {
    ret := _m.Called(ctx, serviceID)

    var r0 *catalog.Service
    if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.Service); ok {
        r0 = rf(ctx, serviceID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Service)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, serviceID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// GetServiceBySKU provides a mock function with given fields: ctx, sku
func (_m *CatalogServiceInterface) GetServiceBySKU(ctx context.Context, sku string) (*catalog.Service, error) {
    ret := _m.Called(ctx, sku)

    var r0 *catalog.Service
    if rf, ok := ret.Get(0).(func(context.Context, string) *catalog.Service); ok {
        r0 = rf(ctx, sku)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Service)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
        r1 = rf(ctx, sku)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// ListCatalogItems provides a mock function with given fields: ctx, filter, offset, limit
func (_m *CatalogServiceInterface) ListCatalogItems(ctx context.Context, filter *requests.CatalogFilter, offset int, limit int) ([]*catalog.CatalogItem, int, error) {
    ret := _m.Called(ctx, filter, offset, limit)

    var r0 []*catalog.CatalogItem
    if rf, ok := ret.Get(0).(func(context.Context, *requests.CatalogFilter, int, int) []*catalog.CatalogItem); ok {
        r0 = rf(ctx, filter, offset, limit)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).([]*catalog.CatalogItem)
        }
    }

    var r1 int
    if rf, ok := ret.Get(1).(func(context.Context, *requests.CatalogFilter, int, int) int); ok {
        r1 = rf(ctx, filter, offset, limit)
    } else {
        r1 = ret.Get(1).(int)
    }

    var r2 error
    if rf, ok := ret.Get(2).(func(context.Context, *requests.CatalogFilter, int, int) error); ok {
        r2 = rf(ctx, filter, offset, limit)
    } else {
        r2 = ret.Error(2)
    }

    return r0, r1, r2
}

// ListLabour provides a mock function with given fields: ctx, limit, offset, category, status
func (_m *CatalogServiceInterface) ListLabour(ctx context.Context, limit int, offset int, category string, status string) ([]*catalog.CatalogItem, error) {
    ret := _m.Called(ctx, limit, offset, category, status)

    var r0 []*catalog.CatalogItem
    if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*catalog.CatalogItem); ok {
        r0 = rf(ctx, limit, offset, category, status)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).([]*catalog.CatalogItem)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
        r1 = rf(ctx, limit, offset, category, status)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// ListProducts provides a mock function with given fields: ctx, limit, offset, category, status
func (_m *CatalogServiceInterface) ListProducts(ctx context.Context, limit int, offset int, category string, status string) ([]*catalog.CatalogItem, error) {
    ret := _m.Called(ctx, limit, offset, category, status)

    var r0 []*catalog.CatalogItem
    if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*catalog.CatalogItem); ok {
        r0 = rf(ctx, limit, offset, category, status)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).([]*catalog.CatalogItem)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
        r1 = rf(ctx, limit, offset, category, status)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// ListServices provides a mock function with given fields: ctx, limit, offset, category, status
func (_m *CatalogServiceInterface) ListServices(ctx context.Context, limit int, offset int, category string, status string) ([]*catalog.CatalogItem, error) {
    ret := _m.Called(ctx, limit, offset, category, status)

    var r0 []*catalog.CatalogItem
    if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*catalog.CatalogItem); ok {
        r0 = rf(ctx, limit, offset, category, status)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).([]*catalog.CatalogItem)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
        r1 = rf(ctx, limit, offset, category, status)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// SearchCatalog provides a mock function with given fields: ctx, query, filter, offset, limit
func (_m *CatalogServiceInterface) SearchCatalog(ctx context.Context, query string, filter *requests.CatalogFilter, offset int, limit int) ([]*catalog.CatalogItem, int, error) {
    ret := _m.Called(ctx, query, filter, offset, limit)

    var r0 []*catalog.CatalogItem
    if rf, ok := ret.Get(0).(func(context.Context, string, *requests.CatalogFilter, int, int) []*catalog.CatalogItem); ok {
        r0 = rf(ctx, query, filter, offset, limit)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).([]*catalog.CatalogItem)
        }
    }

    var r1 int
    if rf, ok := ret.Get(1).(func(context.Context, string, *requests.CatalogFilter, int, int) int); ok {
        r1 = rf(ctx, query, filter, offset, limit)
    } else {
        r1 = ret.Get(1).(int)
    }

    var r2 error
    if rf, ok := ret.Get(2).(func(context.Context, string, *requests.CatalogFilter, int, int) error); ok {
        r2 = rf(ctx, query, filter, offset, limit)
    } else {
        r2 = ret.Error(2)
    }

    return r0, r1, r2
}

// UpdateInventory provides a mock function with given fields: ctx, itemID, quantity, operation
func (_m *CatalogServiceInterface) UpdateInventory(ctx context.Context, itemID string, quantity float64, operation string) error {
    ret := _m.Called(ctx, itemID, quantity, operation)

    var r0 error
    if rf, ok := ret.Get(0).(func(context.Context, string, float64, string) error); ok {
        r0 = rf(ctx, itemID, quantity, operation)
    } else {
        r0 = ret.Error(0)
    }

    return r0
}

// UpdateLabour provides a mock function with given fields: ctx, labour, userID
func (_m *CatalogServiceInterface) UpdateLabour(ctx context.Context, labour *catalog.Labour, userID string) (*catalog.Labour, error) {
    ret := _m.Called(ctx, labour, userID)

    var r0 *catalog.Labour
    if rf, ok := ret.Get(0).(func(context.Context, *catalog.Labour, string) *catalog.Labour); ok {
        r0 = rf(ctx, labour, userID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Labour)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, *catalog.Labour, string) error); ok {
        r1 = rf(ctx, labour, userID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, product, userID
func (_m *CatalogServiceInterface) UpdateProduct(ctx context.Context, product *catalog.Product, userID string) (*catalog.Product, error) {
    ret := _m.Called(ctx, product, userID)

    var r0 *catalog.Product
    if rf, ok := ret.Get(0).(func(context.Context, *catalog.Product, string) *catalog.Product); ok {
        r0 = rf(ctx, product, userID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Product)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, *catalog.Product, string) error); ok {
        r1 = rf(ctx, product, userID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}

// UpdateService provides a mock function with given fields: ctx, service, userID
func (_m *CatalogServiceInterface) UpdateService(ctx context.Context, service *catalog.Service, userID string) (*catalog.Service, error) {
    ret := _m.Called(ctx, service, userID)

    var r0 *catalog.Service
    if rf, ok := ret.Get(0).(func(context.Context, *catalog.Service, string) *catalog.Service); ok {
        r0 = rf(ctx, service, userID)
    } else {
        if ret.Get(0) != nil {
            r0 = ret.Get(0).(*catalog.Service)
        }
    }

    var r1 error
    if rf, ok := ret.Get(1).(func(context.Context, *catalog.Service, string) error); ok {
        r1 = rf(ctx, service, userID)
    } else {
        r1 = ret.Error(1)
    }

    return r0, r1
}
