// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	catalog "kisanlink-ecom/entities/requests/catalog"

	mock "github.com/stretchr/testify/mock"

	modelscatalog "kisanlink-ecom/entities/models/catalog"
)

// CatalogServiceInterface is an autogenerated mock type for the CatalogServiceInterface type
type CatalogServiceInterface struct {
	mock.Mock
}

// CreateLabour provides a mock function with given fields: ctx, req, userID
func (_m *CatalogServiceInterface) CreateLabour(ctx context.Context, req *catalog.CreateLabourRequest, userID string) (*modelscatalog.Labour, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateLabour")
	}

	var r0 *modelscatalog.Labour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.CreateLabourRequest, string) (*modelscatalog.Labour, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.CreateLabourRequest, string) *modelscatalog.Labour); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Labour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *catalog.CreateLabourRequest, string) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateProduct provides a mock function with given fields: ctx, product, userID
func (_m *CatalogServiceInterface) CreateProduct(ctx context.Context, product *modelscatalog.Product, userID string) (*modelscatalog.Product, error) {
	ret := _m.Called(ctx, product, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *modelscatalog.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Product, string) (*modelscatalog.Product, error)); ok {
		return rf(ctx, product, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Product, string) *modelscatalog.Product); ok {
		r0 = rf(ctx, product, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *modelscatalog.Product, string) error); ok {
		r1 = rf(ctx, product, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateService provides a mock function with given fields: ctx, req, userID
func (_m *CatalogServiceInterface) CreateService(ctx context.Context, req *catalog.CreateServiceRequest, userID string) (*modelscatalog.Service, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateService")
	}

	var r0 *modelscatalog.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.CreateServiceRequest, string) (*modelscatalog.Service, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.CreateServiceRequest, string) *modelscatalog.Service); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *catalog.CreateServiceRequest, string) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteContract provides a mock function with given fields: ctx, contractID, userID
func (_m *CatalogServiceInterface) DeleteContract(ctx context.Context, contractID string, userID string) error {
	ret := _m.Called(ctx, contractID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteContract")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, contractID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLabour provides a mock function with given fields: ctx, labourID, userID
func (_m *CatalogServiceInterface) DeleteLabour(ctx context.Context, labourID string, userID string) error {
	ret := _m.Called(ctx, labourID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLabour")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, labourID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProduct provides a mock function with given fields: ctx, productID, userID
func (_m *CatalogServiceInterface) DeleteProduct(ctx context.Context, productID string, userID string) error {
	ret := _m.Called(ctx, productID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, productID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteService provides a mock function with given fields: ctx, serviceID, userID
func (_m *CatalogServiceInterface) DeleteService(ctx context.Context, serviceID string, userID string) error {
	ret := _m.Called(ctx, serviceID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteService")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, serviceID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCatalogItemByID provides a mock function with given fields: ctx, id
func (_m *CatalogServiceInterface) GetCatalogItemByID(ctx context.Context, id string) (*modelscatalog.CatalogItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalogItemByID")
	}

	var r0 *modelscatalog.CatalogItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelscatalog.CatalogItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelscatalog.CatalogItem); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.CatalogItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetInventoryLevel provides a mock function with given fields: ctx, itemID
func (_m *CatalogServiceInterface) GetInventoryLevel(ctx context.Context, itemID string) (float64, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for GetInventoryLevel")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, itemID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLabourByID provides a mock function with given fields: ctx, labourID
func (_m *CatalogServiceInterface) GetLabourByID(ctx context.Context, labourID string) (*modelscatalog.Labour, error) {
	ret := _m.Called(ctx, labourID)

	if len(ret) == 0 {
		panic("no return value specified for GetLabourByID")
	}

	var r0 *modelscatalog.Labour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelscatalog.Labour, error)); ok {
		return rf(ctx, labourID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelscatalog.Labour); ok {
		r0 = rf(ctx, labourID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Labour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, labourID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLabourBySKU provides a mock function with given fields: ctx, sku
func (_m *CatalogServiceInterface) GetLabourBySKU(ctx context.Context, sku string) (*modelscatalog.Labour, error) {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetLabourBySKU")
	}

	var r0 *modelscatalog.Labour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelscatalog.Labour, error)); ok {
		return rf(ctx, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelscatalog.Labour); ok {
		r0 = rf(ctx, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Labour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, productID
func (_m *CatalogServiceInterface) GetProductByID(ctx context.Context, productID string) (*modelscatalog.Product, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *modelscatalog.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelscatalog.Product, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelscatalog.Product); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductBySKU provides a mock function with given fields: ctx, sku
func (_m *CatalogServiceInterface) GetProductBySKU(ctx context.Context, sku string) (*modelscatalog.Product, error) {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetProductBySKU")
	}

	var r0 *modelscatalog.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelscatalog.Product, error)); ok {
		return rf(ctx, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelscatalog.Product); ok {
		r0 = rf(ctx, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceByID provides a mock function with given fields: ctx, serviceID
func (_m *CatalogServiceInterface) GetServiceByID(ctx context.Context, serviceID string) (*modelscatalog.Service, error) {
	ret := _m.Called(ctx, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceByID")
	}

	var r0 *modelscatalog.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelscatalog.Service, error)); ok {
		return rf(ctx, serviceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelscatalog.Service); ok {
		r0 = rf(ctx, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, serviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetServiceBySKU provides a mock function with given fields: ctx, sku
func (_m *CatalogServiceInterface) GetServiceBySKU(ctx context.Context, sku string) (*modelscatalog.Service, error) {
	ret := _m.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceBySKU")
	}

	var r0 *modelscatalog.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*modelscatalog.Service, error)); ok {
		return rf(ctx, sku)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *modelscatalog.Service); ok {
		r0 = rf(ctx, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListCatalogItems provides a mock function with given fields: ctx, filter, offset, limit
func (_m *CatalogServiceInterface) ListCatalogItems(ctx context.Context, filter *catalog.CatalogFilter, offset int, limit int) ([]*modelscatalog.CatalogItem, int, error) {
	ret := _m.Called(ctx, filter, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListCatalogItems")
	}

	var r0 []*modelscatalog.CatalogItem
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.CatalogFilter, int, int) ([]*modelscatalog.CatalogItem, int, error)); ok {
		return rf(ctx, filter, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *catalog.CatalogFilter, int, int) []*modelscatalog.CatalogItem); ok {
		r0 = rf(ctx, filter, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modelscatalog.CatalogItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *catalog.CatalogFilter, int, int) int); ok {
		r1 = rf(ctx, filter, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *catalog.CatalogFilter, int, int) error); ok {
		r2 = rf(ctx, filter, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListLabour provides a mock function with given fields: ctx, limit, offset, category, status
func (_m *CatalogServiceInterface) ListLabour(ctx context.Context, limit int, offset int, category string, status string) ([]*modelscatalog.CatalogItem, error) {
	ret := _m.Called(ctx, limit, offset, category, status)

	if len(ret) == 0 {
		panic("no return value specified for ListLabour")
	}

	var r0 []*modelscatalog.CatalogItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) ([]*modelscatalog.CatalogItem, error)); ok {
		return rf(ctx, limit, offset, category, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*modelscatalog.CatalogItem); ok {
		r0 = rf(ctx, limit, offset, category, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modelscatalog.CatalogItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
		r1 = rf(ctx, limit, offset, category, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProducts provides a mock function with given fields: ctx, limit, offset, category, status
func (_m *CatalogServiceInterface) ListProducts(ctx context.Context, limit int, offset int, category string, status string) ([]*modelscatalog.CatalogItem, error) {
	ret := _m.Called(ctx, limit, offset, category, status)

	if len(ret) == 0 {
		panic("no return value specified for ListProducts")
	}

	var r0 []*modelscatalog.CatalogItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) ([]*modelscatalog.CatalogItem, error)); ok {
		return rf(ctx, limit, offset, category, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*modelscatalog.CatalogItem); ok {
		r0 = rf(ctx, limit, offset, category, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modelscatalog.CatalogItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
		r1 = rf(ctx, limit, offset, category, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListProductsForFPO provides a mock function with given fields: ctx, fpoOrgID, filters, offset, limit
func (_m *CatalogServiceInterface) ListProductsForFPO(ctx context.Context, fpoOrgID string, filters *catalog.CatalogFilter, offset int, limit int) ([]*modelscatalog.ProductWithFPOPricing, error) {
	ret := _m.Called(ctx, fpoOrgID, filters, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListProductsForFPO")
	}

	var r0 []*modelscatalog.ProductWithFPOPricing
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *catalog.CatalogFilter, int, int) ([]*modelscatalog.ProductWithFPOPricing, error)); ok {
		return rf(ctx, fpoOrgID, filters, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *catalog.CatalogFilter, int, int) []*modelscatalog.ProductWithFPOPricing); ok {
		r0 = rf(ctx, fpoOrgID, filters, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modelscatalog.ProductWithFPOPricing)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *catalog.CatalogFilter, int, int) error); ok {
		r1 = rf(ctx, fpoOrgID, filters, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListServices provides a mock function with given fields: ctx, limit, offset, category, status
func (_m *CatalogServiceInterface) ListServices(ctx context.Context, limit int, offset int, category string, status string) ([]*modelscatalog.CatalogItem, error) {
	ret := _m.Called(ctx, limit, offset, category, status)

	if len(ret) == 0 {
		panic("no return value specified for ListServices")
	}

	var r0 []*modelscatalog.CatalogItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) ([]*modelscatalog.CatalogItem, error)); ok {
		return rf(ctx, limit, offset, category, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string) []*modelscatalog.CatalogItem); ok {
		r0 = rf(ctx, limit, offset, category, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modelscatalog.CatalogItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string) error); ok {
		r1 = rf(ctx, limit, offset, category, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchCatalog provides a mock function with given fields: ctx, query, filter, offset, limit
func (_m *CatalogServiceInterface) SearchCatalog(ctx context.Context, query string, filter *catalog.CatalogFilter, offset int, limit int) ([]*modelscatalog.CatalogItem, int, error) {
	ret := _m.Called(ctx, query, filter, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchCatalog")
	}

	var r0 []*modelscatalog.CatalogItem
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *catalog.CatalogFilter, int, int) ([]*modelscatalog.CatalogItem, int, error)); ok {
		return rf(ctx, query, filter, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *catalog.CatalogFilter, int, int) []*modelscatalog.CatalogItem); ok {
		r0 = rf(ctx, query, filter, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*modelscatalog.CatalogItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *catalog.CatalogFilter, int, int) int); ok {
		r1 = rf(ctx, query, filter, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *catalog.CatalogFilter, int, int) error); ok {
		r2 = rf(ctx, query, filter, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateActiveStatus provides a mock function with given fields: ctx, id, isActive, userID
func (_m *CatalogServiceInterface) UpdateActiveStatus(ctx context.Context, id string, isActive bool, userID string) error {
	ret := _m.Called(ctx, id, isActive, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActiveStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, string) error); ok {
		r0 = rf(ctx, id, isActive, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCatalogItem provides a mock function with given fields: ctx, catalogItem, userID
func (_m *CatalogServiceInterface) UpdateCatalogItem(ctx context.Context, catalogItem *modelscatalog.CatalogItem, userID string) (*modelscatalog.CatalogItem, error) {
	ret := _m.Called(ctx, catalogItem, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCatalogItem")
	}

	var r0 *modelscatalog.CatalogItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.CatalogItem, string) (*modelscatalog.CatalogItem, error)); ok {
		return rf(ctx, catalogItem, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.CatalogItem, string) *modelscatalog.CatalogItem); ok {
		r0 = rf(ctx, catalogItem, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.CatalogItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *modelscatalog.CatalogItem, string) error); ok {
		r1 = rf(ctx, catalogItem, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateInventory provides a mock function with given fields: ctx, itemID, quantity, operation
func (_m *CatalogServiceInterface) UpdateInventory(ctx context.Context, itemID string, quantity float64, operation string) error {
	ret := _m.Called(ctx, itemID, quantity, operation)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInventory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, string) error); ok {
		r0 = rf(ctx, itemID, quantity, operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateLabour provides a mock function with given fields: ctx, labour, userID
func (_m *CatalogServiceInterface) UpdateLabour(ctx context.Context, labour *modelscatalog.Labour, userID string) (*modelscatalog.Labour, error) {
	ret := _m.Called(ctx, labour, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLabour")
	}

	var r0 *modelscatalog.Labour
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Labour, string) (*modelscatalog.Labour, error)); ok {
		return rf(ctx, labour, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Labour, string) *modelscatalog.Labour); ok {
		r0 = rf(ctx, labour, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Labour)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *modelscatalog.Labour, string) error); ok {
		r1 = rf(ctx, labour, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProduct provides a mock function with given fields: ctx, product, userID
func (_m *CatalogServiceInterface) UpdateProduct(ctx context.Context, product *modelscatalog.Product, userID string) (*modelscatalog.Product, error) {
	ret := _m.Called(ctx, product, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *modelscatalog.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Product, string) (*modelscatalog.Product, error)); ok {
		return rf(ctx, product, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Product, string) *modelscatalog.Product); ok {
		r0 = rf(ctx, product, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *modelscatalog.Product, string) error); ok {
		r1 = rf(ctx, product, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateService provides a mock function with given fields: ctx, service, userID
func (_m *CatalogServiceInterface) UpdateService(ctx context.Context, service *modelscatalog.Service, userID string) (*modelscatalog.Service, error) {
	ret := _m.Called(ctx, service, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateService")
	}

	var r0 *modelscatalog.Service
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Service, string) (*modelscatalog.Service, error)); ok {
		return rf(ctx, service, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *modelscatalog.Service, string) *modelscatalog.Service); ok {
		r0 = rf(ctx, service, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*modelscatalog.Service)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *modelscatalog.Service, string) error); ok {
		r1 = rf(ctx, service, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCatalogServiceInterface creates a new instance of CatalogServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCatalogServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CatalogServiceInterface {
	mock := &CatalogServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
