// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: proto/auth.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ValidateTokenRequest represents a token validation request
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_proto_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// ValidateTokenResponse represents a token validation response
type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Claims        *TokenClaims           `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_proto_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

// Role represents a role with full details from JWT
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ParentId      string                 `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Permissions   []string               `protobuf:"bytes,7,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Role) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Role) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// UserRole represents a user-role association from JWT
type UserRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Role          *Role                  `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRole) Reset() {
	*x = UserRole{}
	mi := &file_proto_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRole) ProtoMessage() {}

func (x *UserRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRole.ProtoReflect.Descriptor instead.
func (*UserRole) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{3}
}

func (x *UserRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserRole) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRole) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *UserRole) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserRole) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

// Organization represents user organization details
type Organization struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Organization) Reset() {
	*x = Organization{}
	mi := &file_proto_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Organization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Organization) ProtoMessage() {}

func (x *Organization) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Organization.ProtoReflect.Descriptor instead.
func (*Organization) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Organization) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Organization) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Organization) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

// Group represents user group details
type Group struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizationId string                 `protobuf:"bytes,3,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_proto_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{5}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// UserContextDetails represents nested user_context from JWT v2.0
type UserContextDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	IsValidated   bool                   `protobuf:"varint,5,opt,name=is_validated,json=isValidated,proto3" json:"is_validated,omitempty"`
	Roles         []*Role                `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Organizations []*Organization        `protobuf:"bytes,7,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Groups        []*Group               `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContextDetails) Reset() {
	*x = UserContextDetails{}
	mi := &file_proto_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContextDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContextDetails) ProtoMessage() {}

func (x *UserContextDetails) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContextDetails.ProtoReflect.Descriptor instead.
func (*UserContextDetails) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{6}
}

func (x *UserContextDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserContextDetails) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserContextDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UserContextDetails) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *UserContextDetails) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

func (x *UserContextDetails) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *UserContextDetails) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *UserContextDetails) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

// TokenClaims represents JWT token claims
type TokenClaims struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username         string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CountryCode      string                 `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	TenantId         string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,7,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	OrganizationName string                 `protobuf:"bytes,8,opt,name=organization_name,json=organizationName,proto3" json:"organization_name,omitempty"`
	Roles            []string               `protobuf:"bytes,9,rep,name=roles,proto3" json:"roles,omitempty"`
	RoleIds          []string               `protobuf:"bytes,10,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	Permissions      []string               `protobuf:"bytes,11,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Scopes           []string               `protobuf:"bytes,12,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IssuedAt         int64                  `protobuf:"varint,13,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt        int64                  `protobuf:"varint,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	NotBefore        int64                  `protobuf:"varint,15,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	Issuer           string                 `protobuf:"bytes,16,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience         string                 `protobuf:"bytes,17,opt,name=audience,proto3" json:"audience,omitempty"`
	IsValidated      bool                   `protobuf:"varint,18,opt,name=is_validated,json=isValidated,proto3" json:"is_validated,omitempty"`
	UserRoles        []*UserRole            `protobuf:"bytes,19,rep,name=user_roles,json=userRoles,proto3" json:"user_roles,omitempty"`
	Organizations    []*Organization        `protobuf:"bytes,20,rep,name=organizations,proto3" json:"organizations,omitempty"`
	Groups           []*Group               `protobuf:"bytes,21,rep,name=groups,proto3" json:"groups,omitempty"`
	TokenType        string                 `protobuf:"bytes,22,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	TokenVersion     string                 `protobuf:"bytes,23,opt,name=token_version,json=tokenVersion,proto3" json:"token_version,omitempty"`
	Sub              string                 `protobuf:"bytes,24,opt,name=sub,proto3" json:"sub,omitempty"`
	SessionId        string                 `protobuf:"bytes,25,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Jti              string                 `protobuf:"bytes,26,opt,name=jti,proto3" json:"jti,omitempty"`
	TenantContext    string                 `protobuf:"bytes,27,opt,name=tenant_context,json=tenantContext,proto3" json:"tenant_context,omitempty"` // JSON string for flexibility
	UserContext      *UserContextDetails    `protobuf:"bytes,28,opt,name=user_context,json=userContext,proto3" json:"user_context,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_proto_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{7}
}

func (x *TokenClaims) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenClaims) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TokenClaims) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TokenClaims) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *TokenClaims) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *TokenClaims) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TokenClaims) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *TokenClaims) GetOrganizationName() string {
	if x != nil {
		return x.OrganizationName
	}
	return ""
}

func (x *TokenClaims) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *TokenClaims) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *TokenClaims) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *TokenClaims) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *TokenClaims) GetIssuedAt() int64 {
	if x != nil {
		return x.IssuedAt
	}
	return 0
}

func (x *TokenClaims) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *TokenClaims) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *TokenClaims) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TokenClaims) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *TokenClaims) GetIsValidated() bool {
	if x != nil {
		return x.IsValidated
	}
	return false
}

func (x *TokenClaims) GetUserRoles() []*UserRole {
	if x != nil {
		return x.UserRoles
	}
	return nil
}

func (x *TokenClaims) GetOrganizations() []*Organization {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *TokenClaims) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *TokenClaims) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenClaims) GetTokenVersion() string {
	if x != nil {
		return x.TokenVersion
	}
	return ""
}

func (x *TokenClaims) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *TokenClaims) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TokenClaims) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *TokenClaims) GetTenantContext() string {
	if x != nil {
		return x.TenantContext
	}
	return ""
}

func (x *TokenClaims) GetUserContext() *UserContextDetails {
	if x != nil {
		return x.UserContext
	}
	return nil
}

// AuthorizeRequest represents an authorization request
type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_proto_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{8}
}

func (x *AuthorizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthorizeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AuthorizeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthorizeRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

// AuthorizeResponse represents an authorization response
type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_proto_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{9}
}

func (x *AuthorizeResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AuthorizeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// HealthCheckRequest represents a health check request
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{10}
}

// HealthCheckResponse represents a health check response
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_auth_proto protoreflect.FileDescriptor

const file_proto_auth_proto_rawDesc = "" +
	"\n" +
	"\x10proto/auth.proto\x12\x04auth\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"X\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12)\n" +
	"\x06claims\x18\x02 \x01(\v2\x11.auth.TokenClaimsR\x06claims\"\xbe\x01\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\tR\bparentId\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12 \n" +
	"\vpermissions\x18\a \x03(\tR\vpermissions\"\x89\x01\n" +
	"\bUserRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x1e\n" +
	"\x04role\x18\x05 \x01(\v2\n" +
	".auth.RoleR\x04role\"O\n" +
	"\fOrganization\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"v\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0forganization_id\x18\x03 \x01(\tR\x0eorganizationId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xaa\x02\n" +
	"\x12UserContextDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12!\n" +
	"\fis_validated\x18\x05 \x01(\bR\visValidated\x12 \n" +
	"\x05roles\x18\x06 \x03(\v2\n" +
	".auth.RoleR\x05roles\x128\n" +
	"\rorganizations\x18\a \x03(\v2\x12.auth.OrganizationR\rorganizations\x12#\n" +
	"\x06groups\x18\b \x03(\v2\v.auth.GroupR\x06groups\"\xa7\a\n" +
	"\vTokenClaims\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x04 \x01(\tR\vphoneNumber\x12!\n" +
	"\fcountry_code\x18\x05 \x01(\tR\vcountryCode\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\x12'\n" +
	"\x0forganization_id\x18\a \x01(\tR\x0eorganizationId\x12+\n" +
	"\x11organization_name\x18\b \x01(\tR\x10organizationName\x12\x14\n" +
	"\x05roles\x18\t \x03(\tR\x05roles\x12\x19\n" +
	"\brole_ids\x18\n" +
	" \x03(\tR\aroleIds\x12 \n" +
	"\vpermissions\x18\v \x03(\tR\vpermissions\x12\x16\n" +
	"\x06scopes\x18\f \x03(\tR\x06scopes\x12\x1b\n" +
	"\tissued_at\x18\r \x01(\x03R\bissuedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\x03R\texpiresAt\x12\x1d\n" +
	"\n" +
	"not_before\x18\x0f \x01(\x03R\tnotBefore\x12\x16\n" +
	"\x06issuer\x18\x10 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x11 \x01(\tR\baudience\x12!\n" +
	"\fis_validated\x18\x12 \x01(\bR\visValidated\x12-\n" +
	"\n" +
	"user_roles\x18\x13 \x03(\v2\x0e.auth.UserRoleR\tuserRoles\x128\n" +
	"\rorganizations\x18\x14 \x03(\v2\x12.auth.OrganizationR\rorganizations\x12#\n" +
	"\x06groups\x18\x15 \x03(\v2\v.auth.GroupR\x06groups\x12\x1d\n" +
	"\n" +
	"token_type\x18\x16 \x01(\tR\ttokenType\x12#\n" +
	"\rtoken_version\x18\x17 \x01(\tR\ftokenVersion\x12\x10\n" +
	"\x03sub\x18\x18 \x01(\tR\x03sub\x12\x1d\n" +
	"\n" +
	"session_id\x18\x19 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03jti\x18\x1a \x01(\tR\x03jti\x12%\n" +
	"\x0etenant_context\x18\x1b \x01(\tR\rtenantContext\x12;\n" +
	"\fuser_context\x18\x1c \x01(\v2\x18.auth.UserContextDetailsR\vuserContext\"\x9d\x01\n" +
	"\x10AuthorizeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\"E\n" +
	"\x11AuthorizeResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9b\x01\n" +
	"\vAuthService\x12H\n" +
	"\rValidateToken\x12\x1a.auth.ValidateTokenRequest\x1a\x1b.auth.ValidateTokenResponse\x12B\n" +
	"\vHealthCheck\x12\x18.auth.HealthCheckRequest\x1a\x19.auth.HealthCheckResponse2T\n" +
	"\x14AuthorizationService\x12<\n" +
	"\tAuthorize\x12\x16.auth.AuthorizeRequest\x1a\x17.auth.AuthorizeResponseB Z\x1egithub.com/Kisanlink/pkg/protob\x06proto3"

var (
	file_proto_auth_proto_rawDescOnce sync.Once
	file_proto_auth_proto_rawDescData []byte
)

func file_proto_auth_proto_rawDescGZIP() []byte {
	file_proto_auth_proto_rawDescOnce.Do(func() {
		file_proto_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)))
	})
	return file_proto_auth_proto_rawDescData
}

var file_proto_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_auth_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),  // 0: auth.ValidateTokenRequest
	(*ValidateTokenResponse)(nil), // 1: auth.ValidateTokenResponse
	(*Role)(nil),                  // 2: auth.Role
	(*UserRole)(nil),              // 3: auth.UserRole
	(*Organization)(nil),          // 4: auth.Organization
	(*Group)(nil),                 // 5: auth.Group
	(*UserContextDetails)(nil),    // 6: auth.UserContextDetails
	(*TokenClaims)(nil),           // 7: auth.TokenClaims
	(*AuthorizeRequest)(nil),      // 8: auth.AuthorizeRequest
	(*AuthorizeResponse)(nil),     // 9: auth.AuthorizeResponse
	(*HealthCheckRequest)(nil),    // 10: auth.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 11: auth.HealthCheckResponse
}
var file_proto_auth_proto_depIdxs = []int32{
	7,  // 0: auth.ValidateTokenResponse.claims:type_name -> auth.TokenClaims
	2,  // 1: auth.UserRole.role:type_name -> auth.Role
	2,  // 2: auth.UserContextDetails.roles:type_name -> auth.Role
	4,  // 3: auth.UserContextDetails.organizations:type_name -> auth.Organization
	5,  // 4: auth.UserContextDetails.groups:type_name -> auth.Group
	3,  // 5: auth.TokenClaims.user_roles:type_name -> auth.UserRole
	4,  // 6: auth.TokenClaims.organizations:type_name -> auth.Organization
	5,  // 7: auth.TokenClaims.groups:type_name -> auth.Group
	6,  // 8: auth.TokenClaims.user_context:type_name -> auth.UserContextDetails
	0,  // 9: auth.AuthService.ValidateToken:input_type -> auth.ValidateTokenRequest
	10, // 10: auth.AuthService.HealthCheck:input_type -> auth.HealthCheckRequest
	8,  // 11: auth.AuthorizationService.Authorize:input_type -> auth.AuthorizeRequest
	1,  // 12: auth.AuthService.ValidateToken:output_type -> auth.ValidateTokenResponse
	11, // 13: auth.AuthService.HealthCheck:output_type -> auth.HealthCheckResponse
	9,  // 14: auth.AuthorizationService.Authorize:output_type -> auth.AuthorizeResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_auth_proto_init() }
func file_proto_auth_proto_init() {
	if File_proto_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_proto_rawDesc), len(file_proto_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_auth_proto_goTypes,
		DependencyIndexes: file_proto_auth_proto_depIdxs,
		MessageInfos:      file_proto_auth_proto_msgTypes,
	}.Build()
	File_proto_auth_proto = out.File
	file_proto_auth_proto_goTypes = nil
	file_proto_auth_proto_depIdxs = nil
}
