package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/Kisanlink/kisanlink-db/pkg/db"

	_ "kisanlink-ecom/docs" // This is generated by swag
	"kisanlink-ecom/internal/auth"
	"kisanlink-ecom/internal/config"
	"kisanlink-ecom/internal/database"
	"kisanlink-ecom/internal/repositories/catalog"
	"kisanlink-ecom/internal/repositories/orders"
	"kisanlink-ecom/internal/routes"
)

// @title KisanLink E-commerce API
// @version 1.0
// @description This is the KisanLink E-commerce service API.
// @host localhost:8080
// @BasePath /
func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Convert to multi-DB config
	multiDBConfig := config.MultiDatabaseConfig{
		PostgreSQL: config.PostgreSQLConfig{
			Host:         cfg.Database.Host,
			Port:         cfg.Database.Port,
			Database:     cfg.Database.Name,
			Username:     cfg.Database.User,
			Password:     cfg.Database.Password,
			SSLMode:      cfg.Database.SSLMode,
			MaxOpenConns: cfg.Database.MaxConns,
			MaxIdleConns: cfg.Database.MaxConns / 2,
		},
		DynamoDB: config.DynamoDBConfig{
			Region:          cfg.Database.Region,
			Endpoint:        "",
			AccessKeyID:     cfg.Database.AccessKey,
			SecretAccessKey: cfg.Database.SecretKey,
			DisableSSL:      false,
			Table:           "kisanlink_ecom", // Default table name
		},
	}

	// Initialize database connection
	dbManager, err := database.NewDatabaseManager(multiDBConfig)
	if err != nil {
		log.Printf("Warning: Database connection failed: %v", err)
		log.Printf("Continuing without database connection...")
		dbManager = nil
	} else {
		defer dbManager.Close()
	}

	// Initialize repositories (not yet used by handlers until services are wired later)
	if dbManager != nil {
		_ = catalog.NewCatalogRepository(dbManager.GetManager(db.BackendGorm))
		_ = orders.NewOrderRepository(dbManager.GetManager(db.BackendGorm))
		log.Println("Database repositories initialized")
	} else {
		log.Println("Skipping repository initialization - no database connection")
	}

	// Initialize AAA client
	aaaClient, err := auth.NewAAAClient(&cfg.AAA)
	if err != nil {
		log.Printf("Warning: AAA client initialization failed: %v", err)
		log.Printf("Continuing without AAA service - authentication will be mocked")
		aaaClient = nil
	} else {
		defer aaaClient.Close()
	}

	// Setup router
	router := routes.SetupRouter(aaaClient)

	// Start Gin server
	addr := fmt.Sprintf(":%s", cfg.Server.Port)
	log.Printf("Starting Gin server on %s (mode=%s) at %s", addr, cfg.Server.Mode, time.Now().Format(time.RFC3339))
	if err := router.Run(addr); err != nil {
		log.Printf("Gin server exited with error: %v", err)
		os.Exit(1)
	}
}
