package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/Kisanlink/kisanlink-db/pkg/db"
	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"

	// This is generated by swag
	"kisanlink-ecom/docs"
	"kisanlink-ecom/internal/auth"
	"kisanlink-ecom/internal/config"
	"kisanlink-ecom/internal/database"
	"kisanlink-ecom/internal/repositories/catalog"
	"kisanlink-ecom/internal/repositories/collaborator"
	"kisanlink-ecom/internal/repositories/inventory"
	"kisanlink-ecom/internal/repositories/orders"
	"kisanlink-ecom/internal/repositories/sequence"
	"kisanlink-ecom/internal/repositories/user"
	"kisanlink-ecom/internal/routes"
	catalogService "kisanlink-ecom/internal/services/catalog"
	collaboratorService "kisanlink-ecom/internal/services/collaborator"
	integrationService "kisanlink-ecom/internal/services/integrations"
	inventoryService "kisanlink-ecom/internal/services/inventory"
	"kisanlink-ecom/internal/services/marketplace"
	orderService "kisanlink-ecom/internal/services/orders"
	sequenceService "kisanlink-ecom/internal/services/sequence"
	userService "kisanlink-ecom/internal/services/user"
)

// @title KisanLink E-commerce API
// @version 1.0
// @description This is the KisanLink E-commerce service API.
// @host localhost:8080
// @BasePath /
func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Update Swagger host to use the configured port
	docs.SwaggerInfo.Host = fmt.Sprintf("localhost:%s", cfg.Server.Port)

	// Convert to multi-DB config
	multiDBConfig := config.MultiDatabaseConfig{
		PostgreSQL: config.PostgreSQLConfig{
			Host:         cfg.Database.Host,
			Port:         cfg.Database.Port,
			Database:     cfg.Database.Name,
			Username:     cfg.Database.User,
			Password:     cfg.Database.Password,
			SSLMode:      cfg.Database.SSLMode,
			MaxOpenConns: cfg.Database.MaxConns,
			MaxIdleConns: cfg.Database.MaxConns / 2,
		},
		DynamoDB: config.DynamoDBConfig{
			Region:          cfg.Database.Region,
			Endpoint:        "",
			AccessKeyID:     cfg.Database.AccessKey,
			SecretAccessKey: cfg.Database.SecretKey,
			DisableSSL:      false,
			Table:           "kisanlink_ecom", // Default table name
		},
	}

	// Initialize database connection with proper error handling
	dbManager, err := database.NewDatabaseManager(multiDBConfig)
	if err != nil {
		log.Printf("Critical: Database connection failed: %v", err)
		log.Printf("Application cannot start without database connection")
		os.Exit(1)
	}

	// Ensure database connection is closed on exit
	defer func() {
		if err := dbManager.Close(); err != nil {
			log.Printf("Error closing database connection: %v", err)
		}
	}()

	// Perform initial health check
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := dbManager.HealthCheck(ctx); err != nil {
		log.Printf("Warning: Database health check failed: %v", err)
		log.Printf("Continuing with potentially unhealthy database connection...")
	} else {
		log.Printf("Database health check passed")
	}

	// Run auto-migrations
	if err := database.RunAutoMigrations(dbManager); err != nil {
		log.Printf("Critical: Auto-migration failed: %v", err)
		log.Printf("Database schema may be inconsistent")
		os.Exit(1)
	}

	// Create additional indexes
	if err := database.CreateIndexes(dbManager); err != nil {
		log.Printf("Warning: Index creation failed: %v", err)
		log.Printf("Performance may be degraded")
	}

	// Initialize repositories with proper database manager injection
	catalogRepo := catalog.NewCatalogRepository(dbManager.GetManager(db.BackendGorm))
	inventoryRepo := inventory.NewInventoryRepository(dbManager.GetManager(db.BackendGorm))
	orderRepo := orders.NewOrderRepository(dbManager.GetManager(db.BackendGorm))
	sequenceRepo := sequence.NewSequenceRepository(dbManager.GetManager(db.BackendGorm))
	userRepo := user.NewUserRepository(dbManager.GetManager(db.BackendGorm))

	// Initialize services with proper dependency injection
	catalogSvc := catalogService.NewCatalogService(catalogRepo)
	inventorySvc := inventoryService.NewInventoryService(inventoryRepo, catalogRepo)
	sequenceSvc := sequenceService.NewSequenceService(sequenceRepo)
	orderSvc := orderService.NewOrderService(orderRepo, catalogSvc, inventorySvc, sequenceSvc)

	log.Println("Database repositories and services initialized successfully")

	// Initialize AAA client
	aaaClient, err := auth.NewClient(&cfg.AAA)
	if err != nil {
		log.Printf("Warning: AAA client initialization failed: %v", err)
		log.Printf("Falling back to mock AAA client for development")
		aaaClient = auth.NewMockClient()
	} else {
		log.Printf("AAA client initialized successfully")
	}

	// Initialize user service (always available for auth)
	userSvc := userService.NewUserService(aaaClient, userRepo)
	log.Println("User service initialized")

	// Initialize integration service (always available)
	webhookSecret := os.Getenv("WEBHOOK_SECRET")
	if webhookSecret == "" {
		webhookSecret = "default-webhook-secret-change-in-production"
		log.Println("Warning: Using default webhook secret. Set WEBHOOK_SECRET environment variable in production.")
	}

	// Create a logrus logger for the integration service
	logrusLogger := logrus.New()
	integrationSvc := integrationService.NewIntegrationService(catalogSvc, orderSvc, logrusLogger, webhookSecret)
	log.Println("Integration service initialized")

	// Initialize collaborator service
	collaboratorRepo := collaborator.NewCollaboratorRepository(dbManager.GetManager(db.BackendGorm))
	collaboratorSvc := collaboratorService.NewCollaboratorService(collaboratorRepo, logrusLogger)
	log.Println("Collaborator service initialized")

	// Setup router with services and database manager for health checks
	router := routes.SetupRouter(aaaClient, catalogSvc, inventorySvc, orderSvc, userSvc, integrationSvc, &marketplace.MarketplaceServices{}, collaboratorSvc)

	// Add database manager to context for health checks
	router.Use(func(c *gin.Context) {
		c.Set("dbManager", dbManager)
		c.Next()
	})

	// Start Gin server
	addr := fmt.Sprintf(":%s", cfg.Server.Port)
	log.Printf("Starting Gin server on %s (mode=%s) at %s", addr, cfg.Server.Mode, time.Now().Format(time.RFC3339))
	if err := router.Run(addr); err != nil {
		log.Printf("Gin server exited with error: %v", err)
		os.Exit(1)
	}
}
