package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"time"

	"github.com/Kisanlink/kisanlink-db/pkg/db"
	"github.com/gin-gonic/gin"
	"github.com/sirupsen/logrus"
	"go.uber.org/zap"

	// This is generated by swag
	"github.com/Kisanlink/kisanlink-ecom/docs"
	"github.com/Kisanlink/kisanlink-ecom/internal/auth"
	"github.com/Kisanlink/kisanlink-ecom/internal/config"
	"github.com/Kisanlink/kisanlink-ecom/internal/database"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/actors"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/catalog"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/collaborator"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/discounts"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/inventory"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/orders"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/roles"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/sequence"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/services"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/taxation"
	"github.com/Kisanlink/kisanlink-ecom/internal/repositories/user"
	"github.com/Kisanlink/kisanlink-ecom/internal/routes"
	actorsService "github.com/Kisanlink/kisanlink-ecom/internal/services/actors"
	catalogService "github.com/Kisanlink/kisanlink-ecom/internal/services/catalog"
	collaboratorService "github.com/Kisanlink/kisanlink-ecom/internal/services/collaborator"
	discountsService "github.com/Kisanlink/kisanlink-ecom/internal/services/discounts"
	integrationService "github.com/Kisanlink/kisanlink-ecom/internal/services/integrations"
	inventoryService "github.com/Kisanlink/kisanlink-ecom/internal/services/inventory"
	"github.com/Kisanlink/kisanlink-ecom/internal/services/marketplace"
	"github.com/Kisanlink/kisanlink-ecom/internal/services/notifications"
	orderService "github.com/Kisanlink/kisanlink-ecom/internal/services/orders"
	rolesService "github.com/Kisanlink/kisanlink-ecom/internal/services/roles"
	sequenceService "github.com/Kisanlink/kisanlink-ecom/internal/services/sequence"
	slaService "github.com/Kisanlink/kisanlink-ecom/internal/services/sla"
	taxationService "github.com/Kisanlink/kisanlink-ecom/internal/services/taxation"
	userService "github.com/Kisanlink/kisanlink-ecom/internal/services/user"
)

// @title KisanLink E-commerce API
// @version 1.0
// @description This is the KisanLink E-commerce service API.
// @host localhost:8080
// @BasePath /
// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
func main() {
	// Load configuration
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	// Update Swagger host to use the configured port
	docs.SwaggerInfo.Host = fmt.Sprintf("localhost:%s", cfg.Server.Port)

	// Convert to multi-DB config
	multiDBConfig := config.MultiDatabaseConfig{
		PostgreSQL: config.PostgreSQLConfig{
			Host:         cfg.Database.Host,
			Port:         cfg.Database.Port,
			Database:     cfg.Database.Name,
			Username:     cfg.Database.User,
			Password:     cfg.Database.Password,
			SSLMode:      cfg.Database.SSLMode,
			MaxOpenConns: cfg.Database.MaxConns,
			MaxIdleConns: cfg.Database.MaxConns / 2,
		},
		DynamoDB: config.DynamoDBConfig{
			Region:          cfg.Database.Region,
			Endpoint:        "",
			AccessKeyID:     cfg.Database.AccessKey,
			SecretAccessKey: cfg.Database.SecretKey,
			DisableSSL:      false,
			Table:           "kisanlink_ecom", // Default table name
		},
	}

	// Initialize database connection with proper error handling
	dbManager, err := database.NewDatabaseManager(multiDBConfig)
	if err != nil {
		log.Printf("Critical: Database connection failed: %v", err)
		log.Printf("Application cannot start without database connection")
		os.Exit(1)
	}

	// Ensure database connection is closed on exit
	defer func() {
		if err := dbManager.Close(); err != nil {
			log.Printf("Error closing database connection: %v", err)
		}
	}()

	// Perform initial health check
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if err := dbManager.HealthCheck(ctx); err != nil {
		log.Printf("Warning: Database health check failed: %v", err)
		log.Printf("Continuing with potentially unhealthy database connection...")
	} else {
		log.Printf("Database health check passed")
	}

	// Run auto-migrations
	if err := database.RunAutoMigrations(dbManager); err != nil {
		log.Printf("Critical: Auto-migration failed: %v", err)
		log.Printf("Database schema may be inconsistent")
		os.Exit(1)
	}

	// Create additional indexes
	if err := database.CreateIndexes(dbManager); err != nil {
		log.Printf("Warning: Index creation failed: %v", err)
		log.Printf("Performance may be degraded")
	}

	// Initialize ID counters for all models to prevent duplicate key violations
	if err := database.InitializeAllCounters(dbManager.GetManager(db.BackendGorm)); err != nil {
		log.Printf("Warning: Counter initialization failed: %v", err)
		log.Printf("May experience ID collisions on first requests")
	}

	// Initialize repositories with proper database manager injection
	catalogRepo := catalog.NewCatalogRepository(dbManager.GetManager(db.BackendGorm))
	publishStateRepo := catalog.NewPublishStateRepository(dbManager.GetManager(db.BackendGorm))
	inventoryRepo := inventory.NewInventoryRepository(dbManager.GetManager(db.BackendGorm))
	alertRepo := inventory.NewAlertRepository(dbManager.GetManager(db.BackendGorm))
	orderRepo := orders.NewOrderRepository(dbManager.GetManager(db.BackendGorm))
	invoiceRepo := orders.NewInvoiceRepository(dbManager.GetManager(db.BackendGorm))
	purchaseOrderRepo := orders.NewPurchaseOrderRepository(dbManager.GetManager(db.BackendGorm))
	paymentScreenshotRepo := orders.NewPaymentScreenshotRepository(dbManager.GetManager(db.BackendGorm))
	sequenceRepo := sequence.NewSequenceRepository(dbManager.GetManager(db.BackendGorm))
	userRepo := user.NewUserRepository(dbManager.GetManager(db.BackendGorm))
	userRoleRepo := roles.NewUserRoleRepository(dbManager.GetManager(db.BackendGorm))
	orgRoleRepo := roles.NewOrganizationRoleRepository(dbManager.GetManager(db.BackendGorm))
	ecomRoleRepo := roles.NewEcommerceRoleRepository(dbManager.GetManager(db.BackendGorm))
	taxExemptionRepo := taxation.NewTaxExemptionRepository(dbManager.GetManager(db.BackendGorm))
	serviceSLARepo := services.NewSLARepository(dbManager.GetManager(db.BackendGorm))
	discountRuleRepo := discounts.NewDiscountRuleRepository(dbManager.GetManager(db.BackendGorm))
	orgCollaboratorRepo := actors.NewCollaboratorRepository(dbManager.GetManager(db.BackendGorm))

	// Create a shared logrus logger for services
	logrusLogger := logrus.New()

	// Create a zap logger for services that require it (S3Manager, PaymentScreenshotService)
	zapLogger, err := zap.NewProduction()
	if err != nil {
		log.Printf("Warning: Failed to create zap logger: %v", err)
		zapLogger = zap.NewNop() // Use no-op logger as fallback
	}
	defer func() {
		if syncErr := zapLogger.Sync(); syncErr != nil {
			log.Printf("Failed to sync zap logger: %v", syncErr)
		}
	}()

	// Initialize services with proper dependency injection
	catalogSvc := catalogService.NewCatalogService(catalogRepo)
	publishSvc := catalogService.NewPublishService(publishStateRepo, catalogRepo, logrusLogger)
	inventorySvc := inventoryService.NewInventoryService(inventoryRepo, catalogRepo)
	notificationSvc := notifications.NewNotificationService()
	alertSvc := inventoryService.NewAlertService(alertRepo, inventoryRepo, notificationSvc)
	sequenceSvc := sequenceService.NewSequenceService(sequenceRepo)
	orderSvc := orderService.NewOrderService(orderRepo, catalogSvc, inventorySvc, sequenceSvc)
	invoiceSvc := orderService.NewInvoiceService(invoiceRepo, orderRepo)
	purchaseOrderSvc := orderService.NewPurchaseOrderService(purchaseOrderRepo)

	// Initialize S3Manager for payment screenshots
	s3Config := &db.Config{
		S3Bucket: os.Getenv("AWS_S3_BUCKET"),
		S3Region: os.Getenv("AWS_S3_REGION"),
	}
	s3Manager := db.NewS3Manager(s3Config, zapLogger)
	if err := s3Manager.Connect(ctx); err != nil {
		log.Printf("Warning: S3Manager initialization failed: %v", err)
		log.Printf("Payment screenshot uploads will not work without S3 configuration")
	}

	// Initialize Payment Screenshot Service
	paymentScreenshotSvc := orderService.NewPaymentScreenshotService(
		paymentScreenshotRepo,
		orderRepo,
		s3Manager,
		os.Getenv("AWS_S3_BUCKET"),
		zapLogger,
	)
	userRoleSvc := rolesService.NewUserRoleService(userRoleRepo)
	orgRoleSvc := rolesService.NewOrganizationRoleService(orgRoleRepo)
	ecomRoleSvc := rolesService.NewEcommerceRoleService(ecomRoleRepo)
	taxExemptionSvc := taxationService.NewTaxExemptionService(taxExemptionRepo)
	serviceSLASvc := slaService.NewServiceSLAService(serviceSLARepo)
	discountRuleSvc := discountsService.NewDiscountRuleService(discountRuleRepo)
	orgCollaboratorSvc := actorsService.NewOrganizationCollaboratorService(orgCollaboratorRepo)

	log.Println("Database repositories and services initialized successfully")

	// Initialize AAA client
	aaaClient, err := auth.NewClient(&cfg.AAA)
	if err != nil {
		log.Printf("Warning: AAA client initialization failed: %v", err)
		log.Printf("Falling back to mock AAA client for development")
		aaaClient = auth.NewMockClient()
	} else {
		log.Printf("AAA client initialized successfully")
	}

	// Initialize user service (always available for auth)
	userSvc := userService.NewUserService(aaaClient, userRepo)
	log.Println("User service initialized")

	// Initialize integration service (always available)
	webhookSecret := os.Getenv("WEBHOOK_SECRET")
	if webhookSecret == "" {
		webhookSecret = "default-webhook-secret-change-in-production"
		log.Println("Warning: Using default webhook secret. Set WEBHOOK_SECRET environment variable in production.")
	}

	integrationSvc := integrationService.NewIntegrationService(catalogSvc, orderSvc, logrusLogger, webhookSecret)
	log.Println("Integration service initialized")

	// Initialize collaborator service
	collaboratorRepo := collaborator.NewCollaboratorRepository(dbManager.GetManager(db.BackendGorm))
	collaboratorSvc := collaboratorService.NewCollaboratorService(collaboratorRepo, logrusLogger)
	log.Println("Collaborator service initialized")

	// Create services container
	services := &routes.Services{
		CatalogSvc:           catalogSvc,
		PublishSvc:           publishSvc,
		InventorySvc:         inventorySvc,
		AlertSvc:             alertSvc,
		OrderSvc:             orderSvc,
		InvoiceSvc:           invoiceSvc,
		PurchaseOrderSvc:     purchaseOrderSvc,
		PaymentScreenshotSvc: paymentScreenshotSvc,
		UserSvc:              userSvc,
		IntegrationSvc:       integrationSvc,
		MarketplaceSvc:       &marketplace.MarketplaceServices{},
		CollaboratorSvc:      collaboratorSvc,
		UserRoleSvc:          userRoleSvc,
		OrgRoleSvc:           orgRoleSvc,
		EcomRoleSvc:          ecomRoleSvc,
		TaxExemptionSvc:      taxExemptionSvc,
		ServiceSLASvc:        serviceSLASvc,
		DiscountRuleSvc:      discountRuleSvc,
		OrgCollaboratorSvc:   orgCollaboratorSvc,
	}

	// Setup router with services and database manager for health checks
	router := routes.SetupRouter(aaaClient, services)

	// Add database manager to context for health checks
	router.Use(func(c *gin.Context) {
		c.Set("dbManager", dbManager)
		c.Next()
	})

	// Start Gin server
	addr := fmt.Sprintf(":%s", cfg.Server.Port)
	log.Printf("Starting Gin server on %s (mode=%s) at %s", addr, cfg.Server.Mode, time.Now().Format(time.RFC3339))
	if err := router.Run(addr); err != nil {
		log.Printf("Gin server exited with error: %v", err)
		os.Exit(1)
	}
}
